module Purust.CodeGen (codegenModule, codegenPrelude, sanitizeIdent, getArity, extractAllArgTypes, extractFinalRetType, codegenExprType) where
import Debug as Debug


import Prelude
import PureScript.Backend.Optimizer.Syntax (BackendSyntax(..), BackendAccessor(..), BackendOperator(..), BackendOperator1(..), BackendOperator2(..), BackendOperatorNum(..), BackendOperatorOrd(..), Pair(..), Level(..))
import PureScript.Backend.Optimizer.Convert (BackendModule, BackendBindingGroup)
import Debug as Debug
import Effect (Effect)
import Effect.Console (log)
import Effect.Unsafe (unsafePerformEffect)
import PureScript.Backend.Optimizer.Semantics (NeutralExpr(..), DataTypeMeta, CtorMeta)
import PureScript.Backend.Optimizer.CoreFn (Ann, ClassDecl, Expr(..), ExprType(..), Ident(..), Literal(..), Module(..), ModuleName(..), ProperName(..), Prop(..), Qualified(..))
import Debug as Debug
import Data.String as String
import Data.Array as Array
import Data.Array.NonEmpty as NonEmptyArray
import Data.Foldable (foldMap)
import Data.Newtype (unwrap)
import Data.Maybe (Maybe(..))
import Data.Tuple (Tuple(..))
import Data.Set (Set)
import Data.Set as Set
import Data.Map (Map)
import Data.Map as Map
import Data.String.Pattern (Pattern(..), Replacement(..))
import Data.Maybe (Maybe(..), fromMaybe)
import Partial.Unsafe (unsafeCrashWith)
import Effect.Ref as Ref
import Effect.Console (log)
import Effect.Unsafe (unsafePerformEffect)

chunkArray :: forall a. Int -> Array a -> Array (Array a)
chunkArray size arr =
  if Array.length arr <= 0 then []
  else [Array.take size arr] <> chunkArray size (Array.drop size arr)

globalConsumed :: Ref.Ref (Set.Set String)
globalConsumed = unsafePerformEffect (Ref.new Set.empty)

globalCaptured :: Ref.Ref (Set.Set String)
globalCaptured = unsafePerformEffect (Ref.new Set.empty)

codegenModule :: Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Module Ann -> BackendModule -> String
codegenModule globalAritiesMap globalClassFields (Module coreFnMod) backendMod =
  let
    modNameStr = String.replaceAll (Pattern ".") (Replacement "_") (unwrap backendMod.name)
    
    -- Traduction des Enums (ADTs)
    enumsCode = String.joinWith "\n" $ map (\decl ->
      let 
        enumName = sanitizeIdent decl.name
        ctors = map (\ctor ->
          let ctorNameClean = sanitizeIdent ctor.name
              fields = map (\fieldTy -> codegenExprType modNameStr false fieldTy) ctor.fields
          in "    " <> ctorNameClean <> if Array.length fields > 0 then "(" <> String.joinWith ", " fields <> ")" else ""
        ) decl.constructors
      in
        "#[derive(Clone)]\npub enum " <> enumName <> " {\n" <> String.joinWith ",\n" ctors <> "\n}\n"
    ) coreFnMod.dataDecls

    -- Traduction des Classes (Type Classes)
    classesCode = String.joinWith "\n" $ map (\(classDecl :: ClassDecl) ->
      let 
        className = sanitizeIdent classDecl.name
        
        superFields = Array.mapWithIndex (\i (Tuple fqn _) ->
          let scName = fromMaybe "Super" (Array.last fqn)
          in "    pub " <> scName <> show i <> ": crate::UnknownType"
        ) classDecl.superclasses
        
        methFields = map (\(Tuple mName mTy) ->
          "    pub " <> sanitizeIdent mName <> ": " <> codegenExprType modNameStr false mTy
        ) classDecl.methods
        
        fieldsCode = String.joinWith ",\n" (Array.concat [superFields, methFields])
      in
        "#[derive(Clone)]\npub struct " <> className <> " {\n" <> fieldsCode <> "\n}\n"
    ) coreFnMod.classDecls

    -- Traduction des Bindings
    bindingsRes = Array.foldl (\acc group -> 
      let res = codegenBindingGroup coreFnMod.name modNameStr Set.empty Set.empty acc.arities globalClassFields group
      in { code: acc.code <> res.code, arities: res.arities }
    ) { code: "", arities: globalAritiesMap } backendMod.bindings
    
    bindingsCode = bindingsRes.code
    
  in
    "// Code generated by purust for module " <> modNameStr <> "\n\n" <>
    enumsCode <> "\n" <>
    classesCode <> "\n" <>
    bindingsCode

codegenPrelude :: Set.Set String -> String
codegenPrelude fields =
  "#![allow(warnings)]\n\n" <>
  "use perceus_ptr::PerceusPtr;\n\n" <>
  "#[derive(Clone)]\npub enum Void {}\n\n" <>
  "#[derive(Clone)]\n" <>
  "pub enum Value {\n" <>
  "    Int(i64),\n" <>
  "    Number(f64),\n" <>
  "    Bool(bool),\n" <>
  "    String(String),\n" <>
  "    Char(char),\n" <>
  "    Array(std::rc::Rc<Vec<UnknownType>>),\n" <>
  "    Func(std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>),\n" <>
  "    Record(perceus_ptr::PerceusPtr<Record_a>),\n" <>
  "    Class(std::rc::Rc<dyn std::any::Any>),\n" <>
  "}\n\n" <>
  "impl Value {\n" <>
  "    pub fn unwrap_int(&self) -> i64 {\n" <>
  "        if let Value::Int(v) = self { *v } else { panic!(\"Expected Int\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_number(&self) -> f64 {\n" <>
  "        if let Value::Number(v) = self { *v } else { panic!(\"Expected Number\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_bool(&self) -> bool {\n" <>
  "        if let Value::Bool(v) = self { *v } else { panic!(\"Expected Bool\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_string(&self) -> String {\n" <>
  "        if let Value::String(v) = self { v.clone() } else { panic!(\"Expected String\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_char(&self) -> char {\n" <>
  "        if let Value::Char(v) = self { *v } else { panic!(\"Expected Char\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_array(&self) -> std::rc::Rc<Vec<UnknownType>> {\n" <>
  "        if let Value::Array(v) = self { v.clone() } else { panic!(\"Expected Array\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_func(&self) -> std::rc::Rc<dyn Fn(UnknownType) -> UnknownType> {\n" <>
  "        if let Value::Func(v) = self { v.clone() } else if let Value::Record(v) = self { v.call.clone().unwrap() } else { panic!(\"Expected Func\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_record(&self) -> perceus_ptr::PerceusPtr<Record_a> {\n" <>
  "        if let Value::Record(v) = self { v.clone() } else { panic!(\"Expected Record\"); }\n" <>
  "    }\n" <>
  "    pub fn as_record_mut(&mut self) -> &mut perceus_ptr::PerceusPtr<Record_a> {\n" <>
  "        if let Value::Record(v) = self { v } else { panic!(\"Expected Record\"); }\n" <>
  "    }\n" <>
  "    pub fn unwrap_class<T: 'static>(&self) -> &T {\n" <>
  "        if let Value::Class(v) = self { v.downcast_ref::<T>().unwrap() } else { panic!(\"Expected Class\"); }\n" <>
  "    }\n" <>
  "    pub fn drop_explicit(self) {\n" <>
  "        if let Value::Record(v) = self { v.drop_explicit(); }\n" <>
  "    }\n" <>
  "    pub fn new(r: Record_a) -> Self {\n" <>
  "        Value::Record(perceus_ptr::PerceusPtr::new(r))\n" <>
  "    }\n" <>
  "}\n\n" <>
  "pub type UnknownType = Value;\n\n" <>
  "pub fn mk_int(val: i64) -> UnknownType { Value::Int(val) }\n" <>
  "pub fn mk_bool(val: bool) -> UnknownType { Value::Bool(val) }\n" <>
  "pub fn mk_number(val: f64) -> UnknownType { Value::Number(val) }\n" <>
  "pub fn mk_string(val: &str) -> UnknownType { Value::String(val.to_string()) }\n" <>
  "pub fn mk_char(val: char) -> UnknownType { Value::Char(val) }\n" <>
  "pub fn mk_array(val: Vec<UnknownType>) -> UnknownType { Value::Array(std::rc::Rc::new(val)) }\n\n" <>
  "#[derive(Clone, Default)]\npub struct Record_a {\n" <>
  "    pub tag: &'static str,\n" <>
  "    pub vals: Option<std::rc::Rc<Vec<UnknownType>>>,\n" <>
  "    pub call: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
  Array.foldMap (\field ->
    let
      ignore = Set.fromFoldable ["unwrap", "clone", "as_ref", "tag", "vals", "call"]
    in if Set.member field ignore then "" else "    pub " <> sanitizeIdent field <> ": Option<UnknownType>,\n"
  ) (Array.fromFoldable fields) <>
  "}\n\n"
    
unwrapType :: ExprType -> ExprType
unwrapType (ForAll _ t) = unwrapType t
unwrapType (TypeApp t _) = unwrapType t
unwrapType (ConstrainedType cs t) = 
  let csArgs = map (\(Tuple fqn args) -> 
        let className = fromMaybe "" (Array.last fqn)
        in ADT className fqn args) cs
  in case unwrapType t of
    Func args retTy -> Func (csArgs <> args) retTy
    other -> Func csArgs other
unwrapType t = t

debugUnwrap :: String -> ExprType -> ExprType
debugUnwrap name t = 
  let unwrapped = unwrapType t
  in unwrapped

printType :: ExprType -> String
printType (Func _ _) = "Func"
printType (ForAll _ t) = "ForAll(" <> printType t <> ")"
printType (ConstrainedType _ t) = "ConstrainedType(" <> printType t <> ")"
printType (TypeApp a _) = "TypeApp(" <> printType a <> ", [...])"
printType (TypeVar n) = "TypeVar"
printType (Int) = "Int"
printType (Boolean) = "Boolean"
printType Any = "Any"
printType _ = "Other"

codegenExprType :: String -> Boolean -> ExprType -> String
codegenExprType currentMod isRet ty = case unwrapType ty of
  Int -> "i64"
  Boolean -> "bool"
  Number -> "f64"
  String -> "String"
  Char -> "char"
  ADT className fqn _ -> 
    let modName = String.replaceAll (Pattern ".") (Replacement "_") (String.joinWith "_" (Array.dropEnd 1 fqn))
        actualClassName = fromMaybe className (Array.last fqn)
    in if actualClassName == "Void" then "purust_core::Void"
       else if modName == "Prim" || String.indexOf (Pattern "Prim_") modName == Just 0 || String.indexOf (Pattern "Prim") modName == Just 0 then "crate::UnknownType"
           else if modName == "Effect" || modName == "Effect_Exception" || modName == "Effect_Console" || modName == "Effect_Ref" || modName == "Effect_Uncurried" || modName == "Control_Monad_ST_Internal" || modName == "Foreign" || modName == "Data_Array_ST" || String.indexOf (Pattern "Effect_Aff") modName == Just 0 then "crate::UnknownType"
           else if (modName == "Data_Function_Uncurried" || modName == "Control_Monad_ST_Uncurried") && (String.indexOf (Pattern "Fn") actualClassName == Just 0 || String.indexOf (Pattern "STFn") actualClassName == Just 0) then "crate::UnknownType"
           else if modName == currentMod then "std::rc::Rc<crate::" <> sanitizeIdent actualClassName <> ">"
           else "std::rc::Rc<Purs_" <> modName <> "::" <> sanitizeIdent actualClassName <> ">"
  Func args ret -> 
    let retStr = if Array.length args > 1 then codegenExprType currentMod true (Func (Array.drop 1 args) ret) else codegenExprType currentMod true ret
    in "std::rc::Rc<dyn Fn(" <> codegenExprType currentMod false (fromMaybe Any (Array.head args)) <> ") -> " <> retStr <> ">"
  _ -> "crate::UnknownType"

boxUnbox :: String -> ExprType -> ExprType -> String -> String
boxUnbox currentMod expected actual code =
  let
    expStr = codegenExprType currentMod true expected
    actStr = codegenExprType currentMod true actual
    _ = if expStr == "crate::UnknownType" && actStr == "std::rc::Rc<dyn Fn(crate::UnknownType) -> crate::UnknownType>" then Debug.trace ("BOXUNBOX DEBUG: expStr=" <> expStr <> " actStr=" <> actStr <> " expTy=" <> printType expected <> " actTy=" <> printType actual <> " expStr==actStr is " <> show (expStr == actStr)) \_ -> unit else unit
  in
    if String.indexOf (Pattern "unimplemented!()") code == Just 0 || (String.indexOf (Pattern "/* Typed ") code == Just 0 && String.contains (Pattern "unimplemented!()") code && not (String.contains (Pattern "\n") code)) then code
    else if String.drop (String.length code - 15) code == "continue;\n    }" then code
    else if expStr == actStr then code
    else case unwrapType expected, unwrapType actual of
      Func expArgs expRet, Func actArgs actRet ->
        let expArg = fromMaybe Any (Array.head expArgs)
            actArg = fromMaybe Any (Array.head actArgs)
            expRetRem = if Array.length expArgs > 1 then Func (Array.drop 1 expArgs) expRet else expRet
            actRetRem = if Array.length actArgs > 1 then Func (Array.drop 1 actArgs) actRet else actRet
        in "std::rc::Rc::new({ let _f = (" <> code <> ").clone(); move |mut _a: " <> codegenExprType currentMod false expArg <> "| -> " <> codegenExprType currentMod true expRetRem <> " { " <> boxUnbox currentMod expRetRem actRetRem ("_f(" <> boxUnbox currentMod actArg expArg "_a" <> ")") <> " } })"
      
      Func expArgs expRet, _ ->
        let expArg = fromMaybe Any (Array.head expArgs)
            expRetRem = if Array.length expArgs > 1 then Func (Array.drop 1 expArgs) expRet else expRet
            res = if actStr == "crate::UnknownType" || actStr == "crate::Value" then
              "std::rc::Rc::new({ let _f = (" <> code <> ").unwrap_func(); move |mut _a: " <> codegenExprType currentMod false expArg <> "| -> " <> codegenExprType currentMod true expRetRem <> " { " <> boxUnbox currentMod expRetRem Any ("_f(" <> boxUnbox currentMod Any expArg "_a" <> ")") <> " } })"
            else code
        in res

      _, Func actArgs actRet ->
        let actArg = fromMaybe Any (Array.head actArgs)
            actRetRem = if Array.length actArgs > 1 then Func (Array.drop 1 actArgs) actRet else actRet
        in if expStr == "crate::UnknownType" || expStr == "crate::Value" then
          Debug.trace ("BOXUNBOX: expected=" <> printType expected <> ", actual=" <> printType actual <> ", expStr=" <> expStr <> ", code=" <> code) \_ ->
            "crate::Value::Func(std::rc::Rc::new({ let _f = (" <> code <> ").clone(); move |mut _a: crate::UnknownType| -> crate::UnknownType { " <> boxUnbox currentMod Any actRetRem ("_f(" <> boxUnbox currentMod actArg Any "_a" <> ")") <> " } }))"
        else code

      _, _ ->
        let isActADT = case unwrapType actual of 
              ADT _ _ _ -> true
              _ -> false
            isExpADT = case unwrapType expected of
              ADT _ _ _ -> true
              _ -> false
        in if (expStr == "crate::UnknownType" || expStr == "crate::Value") && isActADT then "crate::Value::Class(std::rc::Rc::new(" <> code <> "))"
        else if (actStr == "crate::UnknownType" || actStr == "crate::Value") && isExpADT then "(" <> code <> ").unwrap_class::<" <> expStr <> ">().clone()"
        else if expStr == "i64" && (actStr == "crate::UnknownType" || actStr == "crate::Value") then "(" <> code <> ").unwrap_int()"
        else if (expStr == "crate::UnknownType" || expStr == "crate::Value") && actStr == "i64" then "crate::mk_int(" <> code <> ")"
        else if expStr == "bool" && (actStr == "crate::UnknownType" || actStr == "crate::Value") then "(" <> code <> ").unwrap_bool()"
        else if (expStr == "crate::UnknownType" || expStr == "crate::Value") && actStr == "bool" then "crate::mk_bool(" <> code <> ")"
        else if expStr == "f64" && (actStr == "crate::UnknownType" || actStr == "crate::Value") then "(" <> code <> ").unwrap_number()"
        else if (expStr == "crate::UnknownType" || expStr == "crate::Value") && actStr == "f64" then "crate::mk_number(" <> code <> ")"
        else if expStr == "char" && (actStr == "crate::UnknownType" || actStr == "crate::Value") then "(" <> code <> ").unwrap_char()"
        else if (expStr == "crate::UnknownType" || expStr == "crate::Value") && actStr == "char" then "crate::mk_char(" <> code <> ")"
        else if expStr == "String" && (actStr == "crate::UnknownType" || actStr == "crate::Value") then "(" <> code <> ").unwrap_string()"
        else if (expStr == "crate::UnknownType" || expStr == "crate::Value") && actStr == "String" then "crate::mk_string(&(" <> code <> "))"
        else code

extractAllArgTypes :: ExprType -> Array ExprType
extractAllArgTypes (ForAll _ t) = extractAllArgTypes t
extractAllArgTypes (ConstrainedType cs t) = 
  let csArgs = map (\(Tuple fqn args) -> 
        let className = fromMaybe "" (Array.last fqn)
        in ADT className fqn args) cs
  in csArgs <> extractAllArgTypes t
extractAllArgTypes (Func args t) = args <> extractAllArgTypes t
extractAllArgTypes _ = []

extractFinalRetType :: ExprType -> ExprType
extractFinalRetType (ForAll _ t) = extractFinalRetType t
extractFinalRetType (ConstrainedType _ t) = extractFinalRetType t
extractFinalRetType (Func _ t) = extractFinalRetType t
extractFinalRetType t = t

extractAbsParams :: Int -> NeutralExpr -> Maybe (Tuple (Array String) NeutralExpr)
extractAbsParams 0 expr = Just (Tuple [] expr)
extractAbsParams n (NeutralExpr (Typed _ expr)) = extractAbsParams n expr
extractAbsParams n (NeutralExpr (Abs params body)) = 
  let pNames = map (\(Tuple mbId lvl) -> case mbId of
                 Just (Ident x) -> x
                 Nothing -> "lvl_" <> show (unwrap lvl)) (NonEmptyArray.toArray params)
      len = Array.length pNames
  in if n >= len then
       case extractAbsParams (n - len) body of
         Just (Tuple rest inner) -> Just (Tuple (pNames <> rest) inner)
         Nothing -> Nothing
     else Nothing
extractAbsParams n (NeutralExpr (Let ident ty val body)) =
  case extractAbsParams n body of
    Just (Tuple rest inner) -> Just (Tuple rest (NeutralExpr (Let ident ty val inner)))
    Nothing -> Nothing
extractAbsParams _ _ = Nothing

codegenBindingGroup :: ModuleName -> String -> Set.Set String -> Set.Set String -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> BackendBindingGroup Ident NeutralExpr -> { code :: String, arities :: Map.Map String ExprType }
codegenBindingGroup modName modNameStr allZeroArity allMacroBindings aritiesMap globalClassFields group = unsafePerformEffect do
  Ref.write Set.empty globalConsumed
  pure $ if Array.null group.bindings then { code: "", arities: aritiesMap } else
    let
      isSelfRecursive = group.recursive && Array.length group.bindings == 1
      groupArities = Map.fromFoldable $ map (\(Tuple ident expr) -> 
        let rawIdentName = case ident of
              Ident i -> sanitizeIdent i
              _ -> "unknown"
            identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
            inferredTy = inferTypeExpr modNameStr aritiesMap Map.empty expr
        in Tuple identName inferredTy
      ) group.bindings
      
      mergedArities = Map.union aritiesMap groupArities
      
      code = foldMap (\(Tuple ident expr) ->
      let
        rawIdentName = case ident of
          Ident i -> sanitizeIdent (String.replaceAll (Pattern ".") (Replacement "_") i)
          _ -> "unknown"
        identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
        inferredType = fromMaybe Any (Map.lookup identName mergedArities)
        _dbg = unsafePerformEffect (if identName == "Data_Symbol_reifySymbol" then log ("reifySymbol type: " <> printType inferredType) else pure unit)
        innerExpr = case expr of
           NeutralExpr (Typed _ inner) -> inner
           NeutralExpr inner -> NeutralExpr inner
           _ -> expr
        { paramsCode, retCode, bodyCode, isFunc } =
          let allArgTypes = extractAllArgTypes inferredType
          in if Array.length allArgTypes > 0 then
            let
              retType = extractFinalRetType inferredType
              argTypes = allArgTypes
              extracted = extractAbsParams (Array.length argTypes) innerExpr
              _debug = unsafePerformEffect (log ("FUNCTION " <> identName <> " args: " <> show (Array.length argTypes) <> " extracted: " <> (case extracted of
                Just _ -> "Just"
                Nothing -> "Nothing")))
              isMatchingAbs = case extracted of
                Just _ -> true
                Nothing -> false
              paramsArr = case extracted of
                Just (Tuple p _) -> p
                Nothing -> Array.mapWithIndex (\i _ -> "a" <> show i) argTypes
              deduped = dedupArgs paramsArr
              mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
              paramPairs = Array.zip deduped argTypes
              pCode = String.joinWith ", " $ map (\(Tuple pName ty) ->
                let p = sanitizeIdent pName in
                (if p == "_" then "" else "mut ") <> p <> ": " <> codegenExprType modNameStr true ty) paramPairs
              bound = Map.fromFoldable (map (\(Tuple k v) -> Tuple (if k == "_" then "_" else sanitizeIdent k) v) paramPairs)
              bodyCodeRaw = case extracted of
                Just (Tuple _ body) -> 
                    let bodyRaw = codegenExpr_ modNameStr allZeroArity allMacroBindings mbLoop mergedArities globalClassFields bound Set.empty false body
                        bodyTy = inferTypeExpr modNameStr mergedArities bound body
                    in boxUnbox modNameStr retType bodyTy bodyRaw
                Nothing -> 
                   let fnCode = codegenExpr_ modNameStr allZeroArity allMacroBindings Nothing mergedArities globalClassFields bound Set.empty false innerExpr
                       fnTy = inferTypeExpr modNameStr mergedArities bound innerExpr
                       argsCodeAndType = Array.mapWithIndex (\i p -> let ty = fromMaybe Any (Array.index argTypes i) in Tuple ty (sanitizeIdent p <> ".clone()")) deduped
                       Tuple actualRetTy callCode = Array.foldl (\(Tuple currentTy accCode) (Tuple argTy argCode) ->
                         case unwrapType currentTy of
                           Func argTys nextRetTy ->
                             let expectedArgTy = fromMaybe Any (Array.head argTys)
                                 boxedArg = boxUnbox modNameStr expectedArgTy argTy argCode
                             in Tuple (if Array.length argTys > 1 then Func (Array.drop 1 argTys) nextRetTy else nextRetTy) ("(" <> accCode <> ")(" <> boxedArg <> ")")
                           _ -> 
                             let boxedArg = boxUnbox modNameStr Any argTy argCode
                             in Tuple Any ("(" <> accCode <> ").unwrap_func()(" <> boxedArg <> ")")
                       ) (Tuple fnTy fnCode) argsCodeAndType
                   in boxUnbox modNameStr retType actualRetTy callCode
            in { paramsCode: pCode, retCode: codegenExprType modNameStr true retType, bodyCode: bodyCodeRaw, isFunc: true }
          else 
            let isAbs = case innerExpr of
                  NeutralExpr (Abs _ _) -> true
                  _ -> false
            in if isAbs then
              let
                params = case innerExpr of
                  NeutralExpr (Abs p _) -> p
                  _ -> unsafeCrashWith "impossible"
                paramsArr = map (\(Tuple mbId _) -> case mbId of
                  Just (Ident n) -> n
                  _ -> "_") (NonEmptyArray.toArray params)
                deduped = dedupArgs paramsArr
                mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
                pCode = String.joinWith ", " $ map (\pName ->
                  let p = sanitizeIdent pName in
                  (if p == "_" then "" else "mut ") <> p <> ": UnknownType") deduped
                bound = Map.empty
                body = case innerExpr of
                  NeutralExpr (Abs _ b) -> b
                  _ -> unsafeCrashWith "impossible"
                genResult = genAbs modNameStr allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound Set.empty deduped inferredType body
              in { paramsCode: pCode, retCode: "UnknownType", bodyCode: genResult, isFunc: true }
            else
              { paramsCode: "", retCode: codegenExprType modNameStr true inferredType, bodyCode: codegenExpr_ modNameStr allZeroArity allMacroBindings Nothing aritiesMap globalClassFields Map.empty Set.empty false expr, isFunc: false }
        
        bodyCodeWithLoop = if isSelfRecursive && isFunc then
            "    loop {\n" <>
            "        break " <> bodyCode <> ";\n" <>
            "    }"
          else bodyCode
          
        bodyCodeFinal = bodyCodeWithLoop
      in
        "pub fn " <> identName <> "(" <> paramsCode <> ")" <> (if retCode == "" then "" else " -> " <> retCode) <> " {\n" <>
        "    // AST: " <> printAST expr <> "\n" <>
        bodyCodeFinal <> "\n" <>
        "}\n\n"
      ) group.bindings
    in { code: code, arities: mergedArities }



getTyPrefix :: forall a. String -> Qualified a -> String
getTyPrefix modNameStr (Qualified mbMod _) = case mbMod of
  Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
  Nothing -> String.replaceAll (Pattern ".") (Replacement "_") modNameStr <> "_"


genApp :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Map.Map String ExprType -> Set.Set String -> ExprType -> NeutralExpr -> Array NeutralExpr -> String
genApp modNameStr allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive appTy fn argsArray =
    let buildCall :: ExprType -> String -> Int -> Tuple ExprType String
        buildCall accTy accCode idx = if idx >= Array.length argsCodeArray then Tuple accTy accCode else
            let argCode = fromMaybe "" (Array.index argsCodeArray idx)
                argExpr = fromMaybe (NeutralExpr (Var (Qualified Nothing (Ident "")))) (Array.index argsArray idx)
                argTy = inferTypeExpr modNameStr aritiesMap bound argExpr
            in case unwrapType accTy of
              Func argTys retTy ->
                let expectedArgTy = fromMaybe Any (Array.head argTys)
                    nextRetTy = if Array.length argTys > 1 then Func (Array.drop 1 argTys) retTy else retTy
                    boxedArg = boxUnbox modNameStr expectedArgTy argTy argCode
                in buildCall nextRetTy ("(" <> accCode <> ")(" <> boxedArg <> ")") (idx + 1)
              _ ->
                let boxedArg = boxUnbox modNameStr Any argTy argCode
                in buildCall Any ("(" <> accCode <> ").unwrap_func()(" <> boxedArg <> ")") (idx + 1)
        getInner :: NeutralExpr -> NeutralExpr
        getInner (NeutralExpr (Typed _ inner)) = getInner inner
        getInner e = e
        argsFree = map freeVariables argsArray
        aliveForFn = Set.union alive (Array.foldl Set.union Set.empty argsFree)
        fnCode = codegenExpr_ modNameStr allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForFn false fn
        lookupArity fname = 
          let key = if fname == "main" then "main" else fname
          in case Map.lookup key aritiesMap of
            Just ty -> getArity ty
            Nothing -> 0
            
        argsCodeArray = Array.mapWithIndex (\i arg -> 
            let subsequentArgsFree = Array.drop (i + 1) argsFree
                aliveForArg = Set.union alive (Array.foldl Set.union Set.empty subsequentArgsFree)
            in codegenExpr_ modNameStr allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForArg false arg
          ) argsArray
          
        m = Array.length argsArray
        

        
        resultCode = 
            let mbFnName = case getInner fn of
                  NeutralExpr (Var (Qualified _ (Ident name))) -> Just (sanitizeIdent name)
                  NeutralExpr (Local (Just (Ident name)) _) -> Just (sanitizeIdent name)
                  _ -> Nothing
                isTco = case mbLoop, mbFnName of
                  Just { name: ln, params: lp }, Just n -> (n == ln || (String.replaceAll (Pattern ".") (Replacement "_") modNameStr <> "_" <> n) == ln) && m == Array.length lp
                  _, _ -> false
            in if isTco then
                 case mbLoop of
                   Just { name: ln, params: lp } ->
                       let tempsCode = Array.mapWithIndex (\i argCode -> "        let _tco_temp_" <> show i <> " = " <> argCode <> ";\n") argsCodeArray
                           assignsCode = Array.mapWithIndex (\i pName -> "        " <> sanitizeIdent pName <> " = _tco_temp_" <> show i <> ";\n") lp
                       in "{\n" <> String.joinWith "" tempsCode <> String.joinWith "" assignsCode <> "        continue;\n    }"
                   _ -> ""
               else case getInner fn of
                 NeutralExpr (Var (Qualified mbMod (Ident name))) -> 
                   let sName = sanitizeIdent name
                   in if Map.member sName bound then
                        -- Local variable
                         case buildCall (inferTypeExprGlobal modNameStr aritiesMap globalClassFields bound fn) fnCode 0 of Tuple actualTy callCode -> boxUnbox modNameStr appTy actualTy callCode
                      else
                        let modPrefix = case mbMod of
                              Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
                              Nothing -> String.replaceAll (Pattern ".") (Replacement "_") modNameStr <> "_"
                            fullName = modPrefix <> sName
                        in if fullName == "Data_Eq_eqInt" && m == 2 then
                             "purust_core::mk_bool((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() == (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if fullName == "Data_Semiring_addInt" && m == 2 then
                             "purust_core::mk_int((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() + (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if fullName == "Data_Ring_subInt" && m == 2 then
                             "purust_core::mk_int((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() - (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if fullName == "Data_Semiring_mulInt" && m == 2 then
                             "purust_core::mk_int((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() * (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if fullName == "Data_Ord_lessThanInt" && m == 2 then
                             "purust_core::mk_bool((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() < (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if fullName == "Data_Ord_greaterThanInt" && m == 2 then
                             "purust_core::mk_bool((" <> fromMaybe "" (Array.index argsCodeArray 0) <> ").init_int.unwrap() > (" <> fromMaybe "" (Array.index argsCodeArray 1) <> ").init_int.unwrap())"
                           else if (case mbLoop of
                                 Just { name: ln, params: lp } -> fullName == ln && m == Array.length lp
                                 _ -> false) then
                             case mbLoop of
                               Just { name: ln, params: lp } ->
                                     let tempsCode = Array.mapWithIndex (\i argCode -> "        let _tco_temp_" <> show i <> " = " <> argCode <> ";\n") argsCodeArray
                                         assignsCode = Array.mapWithIndex (\i pName -> "        " <> sanitizeIdent pName <> " = _tco_temp_" <> show i <> ";\n") lp
                                         _dbg = unsafePerformEffect (log ("GENERATED CONTINUE FOR: " <> ln))
                                     in (if _dbg == unit then "" else "") <> "{\n" <>
                                        String.joinWith "" tempsCode <>
                                        String.joinWith "" assignsCode <>
                                        "        continue;\n" <>
                                        "    }"
                               _ -> ""
                           else if Map.member (if fullName == "main" then "main" else fullName) aritiesMap then
                             -- Top-level function
                             let n = lookupArity fullName
                                 fnTy = fromMaybe Any (Map.lookup (if fullName == "main" then "main" else fullName) aritiesMap)
                                 expectedArgTys = extractAllArgTypes fnTy
                                 _ = if fullName == "Control_Monad_ST_Uncurried_runSTFn3" then Debug.trace ("genApp runSTFn3 fnTy: " <> printType fnTy <> " expectedArgTys len: " <> show (Array.length expectedArgTys)) \_ -> unit else unit
                                 boxedArgs = Array.mapWithIndex (\i argCode -> 
                                    let argExpr = fromMaybe (NeutralExpr (Var (Qualified Nothing (Ident "")))) (Array.index argsArray i)
                                        argTy = inferTypeExpr modNameStr aritiesMap bound argExpr
                                        expectedTy = fromMaybe Any (Array.index expectedArgTys i)
                                        _ = if fullName == "Control_Monad_ST_Uncurried_runSTFn3" then Debug.trace ("genApp runSTFn3 arg " <> show i <> ": expectedTy=" <> printType expectedTy <> ", argTy=" <> printType argTy) \_ -> unit else unit
                                    in boxUnbox modNameStr expectedTy argTy argCode
                                 ) argsCodeArray
                             in if n > 0 then
                               if m == n then
                                 fullName <> "(" <> String.joinWith ", " boxedArgs <> ")"
                               else if m < n then
                                 let missingCount = n - m
                                     etaArgs = Array.mapWithIndex (\i _ -> "eta_" <> show i) (Array.replicate missingCount unit)
                                     evalArgs = Array.mapWithIndex (\i _ -> "eval_arg_" <> show i) argsCodeArray
                                     letArgsCode = Array.mapWithIndex (\i boxedArg -> "        let mut eval_arg_" <> show i <> " = " <> boxedArg <> ";\n") boxedArgs
                                     
                                     expectedArgTys = extractAllArgTypes fnTy
                                     missingEtasTypes = Array.drop m expectedArgTys
                                     retTy = extractFinalRetType fnTy

                                     innerArgs = evalArgs <> Array.mapWithIndex (\i eta -> boxUnbox modNameStr (fromMaybe Any (Array.index missingEtasTypes i)) Any (eta <> ".clone()")) etaArgs
                                     innerCall = fullName <> "(" <> String.joinWith ", " innerArgs <> ")"
                                     boxedInnerCall = boxUnbox modNameStr Any retTy innerCall

                                     closuresCode = case Array.foldr (\etaArg (Tuple i accCode) ->
                                         let prevEtas = Array.take i etaArgs
                                             clonesCode = String.joinWith "" (map (\arg -> "    let mut " <> arg <> " = " <> arg <> ".clone();\n") (evalArgs <> prevEtas))
                                         in Tuple (i - 1) ("crate::Value::Func(std::rc::Rc::new(move |mut " <> etaArg <> ": UnknownType| -> UnknownType {\n" <> clonesCode <> "    " <> accCode <> "\n}))")
                                       ) (Tuple (missingCount - 1) boxedInnerCall) etaArgs of
                                       Tuple _ res -> res
                                     blockCode = "{\n" <> String.joinWith "" letArgsCode <> "    " <> closuresCode <> "\n}"
                                 in boxUnbox modNameStr appTy Any blockCode
                               else
                                 let firstNArgs = Array.take n boxedArgs
                                     baseCall = fullName <> "(" <> String.joinWith ", " firstNArgs <> ")"
                                     remainingTy = inferTypeExpr modNameStr aritiesMap bound (Array.foldl (\acc _ -> NeutralExpr (App acc (NonEmptyArray.singleton (NeutralExpr (Var (Qualified Nothing (Ident ""))))))) fn (Array.take n argsArray))
                             in case buildCall remainingTy baseCall n of Tuple actualTy callCode -> boxUnbox modNameStr appTy actualTy callCode
                             else
                               case buildCall (inferTypeExprGlobal modNameStr aritiesMap globalClassFields bound fn) fnCode 0 of Tuple actualTy callCode -> boxUnbox modNameStr appTy actualTy callCode
                           else
                             case buildCall (inferTypeExprGlobal modNameStr aritiesMap globalClassFields bound fn) fnCode 0 of Tuple actualTy callCode -> boxUnbox modNameStr appTy actualTy callCode
                 _ -> 
                   case buildCall (inferTypeExprGlobal modNameStr aritiesMap globalClassFields bound fn) fnCode 0 of Tuple actualTy callCode -> boxUnbox modNameStr appTy actualTy callCode
                   
    in resultCode

genAbs :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Map.Map String ExprType -> Set.Set String -> Array String -> ExprType -> NeutralExpr -> String
genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr fnTy body =
    let
      capturedVars = Set.difference (freeVariables body) (Set.fromFoldable paramsArr)
      expectedArgTys = extractAllArgTypes fnTy
      expectedRetTy = extractFinalRetType fnTy

      newBound = Array.foldr (\(Tuple i p) b -> 
          let pTy = fromMaybe Any (Array.index expectedArgTys i)
          in if p == "_" then b else Map.insert (sanitizeIdent p) pTy b
        ) bound (Array.mapWithIndex Tuple paramsArr)

      initialState = { 
        freeVars: freeVariables body, 
        isInnermost: true, 
        code: 
          let bodyTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields newBound body
              rawCode = unsafePerformEffect do
                oldCaptured <- Ref.read globalCaptured
                _ <- Ref.modify (Set.union capturedVars) globalCaptured
                let res = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields newBound capturedVars false body
                Ref.write oldCaptured globalCaptured
                pure res
              remainingArgs = Array.drop (Array.length paramsArr) expectedArgTys
              innermostExpectedRetTy = if Array.length remainingArgs > 0 then Func remainingArgs expectedRetTy else expectedRetTy
          in boxUnbox currentMod innermostExpectedRetTy bodyTy rawCode
      }
      
      finalState = Array.foldr (\(Tuple i p) st -> 
          let
             pTy = fromMaybe Any (Array.index expectedArgTys i)
             pCode = (if p == "_" then "" else "mut ") <> p <> ": " <> codegenExprType currentMod false pTy
             
             remainingArgTys = Array.drop (i + 1) expectedArgTys
             thisRetTy = if Array.length remainingArgTys > 0 then Func remainingArgTys expectedRetTy else expectedRetTy
             retTyStr = codegenExprType currentMod true thisRetTy
             
             neededByInner = st.freeVars
             pIsUsed = Set.member p neededByInner
             dropsCode = if p /= "_" && not pIsUsed then "    drop(" <> p <> ");\n" else ""
             thisClosureCaptures = Set.delete p neededByInner
             toClone = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity)) (Array.fromFoldable thisClosureCaptures)
             clonesCode = String.joinWith "" (map (\v -> "    let mut " <> sanitizeIdent v <> " = " <> sanitizeIdent v <> ".clone();\n") toClone)
             
             newCode = "std::rc::Rc::new(move |" <> pCode <> "| -> " <> retTyStr <> " {\n" <>
                       clonesCode <> dropsCode <> "    " <> st.code <> "\n" <>
                       "})"
          in { freeVars: thisClosureCaptures, isInnermost: false, code: newCode }
        ) initialState (Array.mapWithIndex Tuple paramsArr)
      
      toCloneOutside = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity)) (Array.fromFoldable (Set.intersection finalState.freeVars alive))
      outsideClonesCode = String.joinWith "" (map (\v -> "let mut " <> sanitizeIdent v <> " = " <> sanitizeIdent v <> ".clone();\n    ") toCloneOutside)
      wrappedCode = if Array.length toCloneOutside > 0 then
          "{\n    " <> outsideClonesCode <> finalState.code <> "\n}"
        else finalState.code
    in wrappedCode

codegenExpr :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Map.Map String ExprType -> Set.Set String -> NeutralExpr -> String
codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive expr =
  codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive false expr

codegenExpr_ :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Map.Map String ExprType -> Set.Set String -> Boolean -> NeutralExpr -> String
codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive inEffectBlock expr@(NeutralExpr syn) = 
  let
    isEffectNode :: NeutralExpr -> Boolean
    isEffectNode (NeutralExpr e) = case e of
      EffectBind _ _ _ _ -> true
      EffectPure _ -> true
      PrimEffect _ -> true
      UncurriedEffectApp _ _ -> true
      Let _ _ _ body -> isEffectNode body
      LetRec _ _ body -> isEffectNode body
      Typed _ inner -> isEffectNode inner
      EffectDefer inner -> isEffectNode inner
      _ -> false
  in
    if isEffectNode expr && not inEffectBlock then
      let
        freeVars = freeVariables expr
        toCloneOutside = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity)) (Array.fromFoldable (Set.intersection freeVars alive))
        outsideClonesCode = String.joinWith "" (map (\v -> "let mut " <> sanitizeIdent v <> " = " <> sanitizeIdent v <> ".clone();\n    ") toCloneOutside)
        toCloneInside = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity)) (Array.fromFoldable freeVars)
        insideClonesCode = "// FREEVARS: " <> String.joinWith ", " (Array.fromFoldable freeVars) <> "\n" <> String.joinWith "" (map (\v -> "    let mut " <> sanitizeIdent v <> " = " <> sanitizeIdent v <> ".clone();\n") toCloneInside)
        bodyCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound freeVars true expr
      in
        if Array.length toCloneOutside > 0 then
          "{\n    " <> outsideClonesCode <> "crate::Value::Func(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {\n" <>
          insideClonesCode <> "        " <> bodyCode <> "\n" <>
          "    }))\n}"
        else
          "{\n    crate::Value::Func(std::rc::Rc::new(move |mut _u: crate::UnknownType| -> crate::UnknownType {\n" <>
          insideClonesCode <> "        " <> bodyCode <> "\n" <>
          "    }))\n}"
    else case syn of
  Typed ty innerRaw -> 
    let 
      stripTyped :: NeutralExpr -> NeutralExpr
      stripTyped (NeutralExpr (Typed _ i)) = stripTyped i
      stripTyped other = other
      inner = stripTyped innerRaw
    in case inner of
      NeutralExpr (Abs params body) ->
        let
          paramsArr = map (\(Tuple mbId lvl) -> case mbId of
            Just (Ident n) -> sanitizeIdent n
            Nothing -> "lvl_" <> show (unwrap lvl)) (NonEmptyArray.toArray params)
          actualTy = 
            let argTys = extractAllArgTypes ty
                retTy = extractFinalRetType ty
                filledArgTys = Array.mapWithIndex (\i _ -> fromMaybe Any (Array.index argTys i)) paramsArr
                remainingArgTys = Array.drop (Array.length paramsArr) argTys
                finalRetTy = if Array.length remainingArgTys > 0 then Func remainingArgTys retTy else retTy
            in Func filledArgTys finalRetTy
        in "/* Typed Abs */" <> boxUnbox currentMod ty actualTy (genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr ty body)
      NeutralExpr (UncurriedAbs params body) ->
        let
          paramsArr = map (\(Tuple mbId lvl) -> case mbId of
            Just (Ident n) -> sanitizeIdent n
            Nothing -> "lvl_" <> show (unwrap lvl)) params
          actualTy = 
            let argTys = extractAllArgTypes ty
                retTy = extractFinalRetType ty
                filledArgTys = Array.mapWithIndex (\i _ -> fromMaybe Any (Array.index argTys i)) paramsArr
                remainingArgTys = Array.drop (Array.length paramsArr) argTys
                finalRetTy = if Array.length remainingArgTys > 0 then Func remainingArgTys retTy else retTy
            in Func filledArgTys finalRetTy
        in "/* Typed UncurriedAbs */" <> boxUnbox currentMod ty actualTy (genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr ty body)
      NeutralExpr (UncurriedEffectAbs params body) ->
        let
          paramsArr = map (\(Tuple mbId lvl) -> case mbId of
            Just (Ident n) -> sanitizeIdent n
            Nothing -> "lvl_" <> show (unwrap lvl)) params
          actualTy = 
            let argTys = extractAllArgTypes ty
                retTy = extractFinalRetType ty
                filledArgTys = Array.mapWithIndex (\i _ -> fromMaybe Any (Array.index argTys i)) paramsArr
                remainingArgTys = Array.drop (Array.length paramsArr) argTys
                finalRetTy = if Array.length remainingArgTys > 0 then Func remainingArgTys retTy else retTy
            in Func filledArgTys finalRetTy
        in "/* Typed UncurriedEffectAbs */" <> boxUnbox currentMod ty actualTy (genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr ty body)
      NeutralExpr (Lit (LitRecord props)) ->
        case unwrapType ty of
          ADT _ fqnParts _ | Array.length fqnParts >= 2 ->
            let
              className = sanitizeIdent (fromMaybe "Unknown" (Array.last fqnParts))
              modName = String.joinWith "_" (Array.dropEnd 1 fqnParts)
              structName = if modName == currentMod then "crate::" <> className else "Purs_" <> modName <> "::" <> className
              propsArr = Array.fromFoldable props
              propsCode = Array.mapWithIndex (\i (Prop p val) ->
                let subsequentProps = Array.drop (i + 1) propsArr
                    aliveForProp = Set.union alive (Array.foldl (\acc (Prop _ sv) -> Set.union acc (freeVariables sv)) Set.empty subsequentProps)
                    valCode = codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound aliveForProp false val
                    valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
                    expectedTy = let findFieldTy k (ADT _ fqn _) =
                                       let modStr = String.joinWith "_" (Array.dropEnd 1 fqn)
                                           nameStr = fromMaybe "" (Array.last fqn)
                                           mbDecl = Map.lookup (modStr <> "_" <> nameStr) globalClassFields
                                       in case mbDecl of
                                            Just classFields -> case Array.find (\(Tuple fn _) -> fn == sanitizeIdent k) classFields of
                                              Just (Tuple _ t) -> t
                                              Nothing -> valTy
                                            Nothing -> valTy
                                     findFieldTy _ _ = valTy
                                 in findFieldTy p (unwrapType ty)
                 in Debug.trace ("LITRECORD expStr=" <> codegenExprType currentMod true expectedTy <> ", actStr=" <> codegenExprType currentMod true valTy <> " for " <> p) \_ -> sanitizeIdent p <> ": " <> boxUnbox currentMod expectedTy valTy valCode
              ) propsArr
              fields = String.joinWith ", " propsCode
            in "std::rc::Rc::new(" <> structName <> " { " <> fields <> " })"
          _ ->
            let innerCode = codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive inEffectBlock inner
                innerTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound inner
            in "/* Typed " <> codegenExprType currentMod true ty <> " <- " <> codegenExprType currentMod true innerTy <> " : " <> printAST inner <> " */" <> boxUnbox currentMod ty innerTy innerCode
      _ ->
        let innerCode = codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive inEffectBlock inner
            innerTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound inner
            fixedTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr (Typed ty inner))
        in "/* Typed " <> codegenExprType currentMod true ty <> " <- " <> codegenExprType currentMod true innerTy <> " : " <> printAST inner <> " */" <> boxUnbox currentMod fixedTy innerTy innerCode

  App fn args -> 
    let appTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr (App fn args))
    in genApp currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive appTy fn (NonEmptyArray.toArray args)
  UncurriedApp fn args ->
    let appTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr (UncurriedApp fn args))
    in genApp currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive appTy fn args
  UncurriedEffectApp fn args -> 
    case fn of
      NeutralExpr (Typed _ (NeutralExpr (Accessor _ (GetProp "logRecord")))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Accessor _ (GetProp "logRecord")) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Typed _ (NeutralExpr (Var (Qualified _ (Ident "logRecord"))))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Var (Qualified _ (Ident "logRecord"))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      _ -> 
        let appTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr (UncurriedEffectApp fn args))
        in genApp currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive appTy fn args

  Update base props ->
    let
      propsArr = props
      propsCode = Array.mapWithIndex (\i (Prop k v) -> 
        let subsequentProps = Array.drop (i + 1) propsArr
            aliveForProp = Set.union alive (Array.foldl (\acc (Prop _ sv) -> Set.union acc (freeVariables sv)) Set.empty subsequentProps)
            valCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForProp false v
            valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound v
        in "_mut." <> sanitizeIdent k <> " = Some(" <> boxUnbox currentMod Any valTy valCode <> ");"
      ) propsArr
      aliveForBase = Set.union alive (Array.foldl (\acc (Prop _ sv) -> Set.union acc (freeVariables sv)) Set.empty propsArr)
    in
      "{\n" <>
      "    let mut _base = " <> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForBase false base <> ";\n" <>
      "    {\n" <>
      "        let _mut = perceus_ptr::PerceusPtr::make_mut(_base.as_record_mut());\n" <>
      "        " <> String.joinWith "\n        " propsCode <> "\n" <>
      "    }\n" <>
      "    _base\n" <>
      "}"
  Branch branches def ->
    let
      branchesArr = NonEmptyArray.toArray branches
      branchCode = Array.mapWithIndex (\i (Pair cond body) -> 
        let 
            subsequentBranches = Array.drop (i + 1) branchesArr
            varsSubsequent = Array.foldl (\acc (Pair c b) -> Set.union acc (Set.union (freeVariables c) (freeVariables b))) (freeVariables def) subsequentBranches
            aliveForCond = Set.union alive (Set.union (freeVariables body) varsSubsequent)
            condCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForCond false cond
            condTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound cond
            condFinal = boxUnbox currentMod Boolean condTy condCode
        in "if " <> condFinal <> " {\n        " <> codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive false body <> "\n    }") branchesArr
      defCode = "{\n        " <> codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive false def <> "\n    }"
    in
      String.joinWith " else " branchCode <> " else " <> defCode
  PrimOp (Op1 op a) ->
    let aTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound a
        aStrRaw = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false a
    in case op of
      OpBooleanNot -> "!(" <> boxUnbox currentMod Boolean aTy aStrRaw <> " /* aTy: " <> codegenExprType currentMod true aTy <> ", a is " <> printAST a <> ", fn ty is " <> (case a of
        NeutralExpr (App fn _) -> printType (inferTypeExprGlobal currentMod aritiesMap globalClassFields bound fn) <> ", lvl_3 in bound: " <> (case Map.lookup "lvl_3" bound of
          Just t -> printType t
          Nothing -> "none") <> ", lvl_3 in arities: " <> (case Map.lookup "lvl_3" aritiesMap of
          Just t -> printType t
          Nothing -> "none")
        _ -> "not app") <> " */)"
      OpIntBitNot -> "!(" <> boxUnbox currentMod Int aTy aStrRaw <> ")"
      OpIntNegate -> "-(" <> boxUnbox currentMod Int aTy aStrRaw <> ")"
      OpNumberNegate -> "-(" <> boxUnbox currentMod Number aTy aStrRaw <> ")"
      OpArrayLength -> "((" <> boxUnbox currentMod Any aTy aStrRaw <> ").unwrap_array().len() as i64)"
      OpIsTag (Qualified mbMod (Ident ctorName)) -> 
        case unwrapType aTy of
          ADT className fqn _ -> 
             let modName = String.replaceAll (Pattern ".") (Replacement "_") (String.joinWith "_" (Array.dropEnd 1 fqn))
                 actualClassName = fromMaybe className (Array.last fqn)
                 enumName = if modName == currentMod then "crate::" <> sanitizeIdent actualClassName else "Purs_" <> modName <> "::" <> sanitizeIdent actualClassName
                 cName = sanitizeIdent ctorName
                 prefixedKey = modName <> "_" <> cName
                 lookupRes = Map.lookup prefixedKey aritiesMap
                 hasArgs = case map unwrapType lookupRes of
                   Just (Func _ _) -> true
                   _ -> false
                 suffix = if hasArgs then "(..)" else ""
                 debugComment = "/* OpIsTag Debug: " <> prefixedKey <> " -> " <> (case lookupRes of
                   Just t -> printType t
                   Nothing -> "Nothing") <> " */ "
             in debugComment <> "matches!((" <> aStrRaw <> ").as_ref(), " <> enumName <> "::" <> cName <> suffix <> ")"
          _ -> "(" <> boxUnbox currentMod Any aTy aStrRaw <> ".unwrap_record().tag == \"" <> ctorName <> "\")"
      _ -> "{ let _t: crate::UnknownType = unimplemented!(); _t } /* Unsupported Op1 */"
  PrimOp (Op2 op a b) ->
    let aliveForA = Set.union alive (freeVariables b)
        aTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound a
        bTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound b
        aStrRaw = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForA false a
        bStrRaw = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false b
        aStrInt = boxUnbox currentMod Int aTy aStrRaw
        bStrInt = boxUnbox currentMod Int bTy bStrRaw
        aStrBool = boxUnbox currentMod Boolean aTy aStrRaw
        bStrBool = boxUnbox currentMod Boolean bTy bStrRaw
        aStrNum = boxUnbox currentMod Number aTy aStrRaw
        bStrNum = boxUnbox currentMod Number bTy bStrRaw
        aStrStr = boxUnbox currentMod String aTy aStrRaw
        bStrStr = boxUnbox currentMod String bTy bStrRaw
    in case op of
      OpIntNum OpAdd -> "(" <> aStrInt <> " + " <> bStrInt <> ")"
      OpIntNum OpSubtract -> "(" <> aStrInt <> " - " <> bStrInt <> ")"
      OpIntNum OpMultiply -> "(" <> aStrInt <> " * " <> bStrInt <> ")"
      OpIntNum OpDivide -> "(" <> aStrInt <> " / " <> bStrInt <> ")"
      OpIntBitAnd -> "(" <> aStrInt <> " & " <> bStrInt <> ")"
      OpIntBitOr -> "(" <> aStrInt <> " | " <> bStrInt <> ")"
      OpIntBitXor -> "(" <> aStrInt <> " ^ " <> bStrInt <> ")"
      OpIntBitShiftLeft -> "(" <> aStrInt <> " << " <> bStrInt <> ")"
      OpIntBitShiftRight -> "(" <> aStrInt <> " >> " <> bStrInt <> ")"
      OpIntBitZeroFillShiftRight -> "((" <> aStrInt <> " as u64 >> " <> bStrInt <> " as u64) as i64)"
      OpIntOrd OpEq -> "(" <> aStrInt <> " == " <> bStrInt <> ")"
      OpIntOrd OpNotEq -> "(" <> aStrInt <> " != " <> bStrInt <> ")"
      OpIntOrd OpGt -> "(" <> aStrInt <> " > " <> bStrInt <> ")"
      OpIntOrd OpGte -> "(" <> aStrInt <> " >= " <> bStrInt <> ")"
      OpIntOrd OpLt -> "(" <> aStrInt <> " < " <> bStrInt <> ")"
      OpIntOrd OpLte -> "(" <> aStrInt <> " <= " <> bStrInt <> ")"
      OpNumberOrd OpEq -> "(" <> aStrNum <> " == " <> bStrNum <> ")"
      OpNumberOrd OpNotEq -> "(" <> aStrNum <> " != " <> bStrNum <> ")"
      OpNumberOrd OpGt -> "(" <> aStrNum <> " > " <> bStrNum <> ")"
      OpNumberOrd OpGte -> "(" <> aStrNum <> " >= " <> bStrNum <> ")"
      OpNumberOrd OpLt -> "(" <> aStrNum <> " < " <> bStrNum <> ")"
      OpNumberOrd OpLte -> "(" <> aStrNum <> " <= " <> bStrNum <> ")"
      OpStringOrd OpEq -> "(" <> aStrStr <> " == " <> bStrStr <> ")"
      OpStringOrd OpNotEq -> "(" <> aStrStr <> " != " <> bStrStr <> ")"
      OpStringOrd OpGt -> "(" <> aStrStr <> " > " <> bStrStr <> ")"
      OpStringOrd OpGte -> "(" <> aStrStr <> " >= " <> bStrStr <> ")"
      OpStringOrd OpLt -> "(" <> aStrStr <> " < " <> bStrStr <> ")"
      OpStringOrd OpLte -> "(" <> aStrStr <> " <= " <> bStrStr <> ")"
      OpCharOrd OpEq -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " == " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpCharOrd OpNotEq -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " != " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpCharOrd OpGt -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " > " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpCharOrd OpGte -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " >= " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpCharOrd OpLt -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " < " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpCharOrd OpLte -> "(" <> boxUnbox currentMod Char aTy aStrRaw <> " <= " <> boxUnbox currentMod Char bTy bStrRaw <> ")"
      OpBooleanOrd OpEq -> "(" <> aStrBool <> " == " <> bStrBool <> ")"
      OpBooleanOrd OpNotEq -> "(" <> aStrBool <> " != " <> bStrBool <> ")"
      OpBooleanOrd OpGt -> "(" <> aStrBool <> " > " <> bStrBool <> ")"
      OpBooleanOrd OpGte -> "(" <> aStrBool <> " >= " <> bStrBool <> ")"
      OpBooleanOrd OpLt -> "(" <> aStrBool <> " < " <> bStrBool <> ")"
      OpBooleanOrd OpLte -> "(" <> aStrBool <> " <= " <> bStrBool <> ")"
      OpBooleanAnd -> "(" <> aStrBool <> " && " <> bStrBool <> ")"
      OpBooleanOr -> "(" <> aStrBool <> " || " <> bStrBool <> ")"
      OpArrayIndex -> 
        let aStr = boxUnbox currentMod Any aTy aStrRaw
        in "(" <> aStr <> ").unwrap_array()[(" <> bStrInt <> ") as usize].clone()"
      OpNumberNum OpAdd -> "(" <> aStrNum <> " + " <> bStrNum <> ")"
      OpNumberNum OpSubtract -> "(" <> aStrNum <> " - " <> bStrNum <> ")"
      OpNumberNum OpMultiply -> "(" <> aStrNum <> " * " <> bStrNum <> ")"
      OpNumberNum OpDivide -> "(" <> aStrNum <> " / " <> bStrNum <> ")"
      OpStringAppend -> "format!(\"{}{}\", " <> aStrStr <> ", " <> bStrStr <> ")"
      _ -> "{ let _t: crate::UnknownType = unimplemented!(); _t } /* Unsupported Op2 */"
  Accessor base (GetProp k) -> 
    let baseStr = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false base
        baseTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound base
        accCode = case unwrapType baseTy of
          ADT className fqn _ ->
            "(" <> baseStr <> ")." <> sanitizeIdent k <> ".clone()"
          _ -> baseStr <> ".unwrap_record()." <> sanitizeIdent k <> ".clone().unwrap()"
        actualTy = case unwrapType baseTy of
          ADT _ _ _ -> inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr syn)
          _ -> Any
    in boxUnbox currentMod (inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr syn)) actualTy accCode
  Accessor base (GetCtorField (Qualified mbMod _) _ (ProperName tyNameStr) (Ident ctorName) _ fieldIdx) ->
    let baseRaw = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false base
        baseTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound base
        modName = case mbMod of
          Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn
          Nothing -> currentMod
        enumName = if modName == currentMod then "crate::" <> sanitizeIdent tyNameStr else "Purs_" <> modName <> "::" <> sanitizeIdent tyNameStr
        cName = sanitizeIdent ctorName
        matchArgs = String.joinWith ", " (map (\i -> if i == fieldIdx then "ref f" else "_") (Array.range 0 fieldIdx)) <> (if fieldIdx >= 0 then ", .." else "")
        expectedBaseTy = ADT tyNameStr [modName, tyNameStr] []
        baseStr = boxUnbox currentMod expectedBaseTy baseTy baseRaw
    in "{ if let " <> enumName <> "::" <> cName <> "(" <> matchArgs <> ") = (" <> baseStr <> ").as_ref() { f.clone() } else { unreachable!() } }"
  Var (Qualified mbMod (Ident name)) ->
    let sName = sanitizeIdent name
        t = case Map.lookup sName bound of
          Just tVal -> tVal
          Nothing -> fromMaybe Any (Map.lookup name aritiesMap)
        _ = if sName == "sup" then Debug.trace ("VAR sup type is: " <> printType t) \_ -> unit else unit
    in case Map.lookup sName bound of
      Just tBound -> 
        let isAlive = Set.member sName alive
            varCode = case unwrapType tBound of
              Func _ _ -> sName
              _ -> sName <> "()"
        in if isAlive then varCode <> ".clone()" else varCode
      Nothing -> 
        let
          modPrefix = case mbMod of
            Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
            Nothing -> String.replaceAll (Pattern ".") (Replacement "_") currentMod <> "_"
          fullName = modPrefix <> sanitizeIdent name
          
          key = if fullName == "main" then "main" else fullName
          isTopLevel = true
          expectedArgsLength = case Map.lookup key aritiesMap of
            Just ty -> getArity ty
            Nothing -> 0

          varCode = if isTopLevel then
            if expectedArgsLength == 0 then
               fullName <> "()"
            else
               let etaArgs = Array.mapWithIndex (\i _ -> "eta_" <> show i) (Array.replicate expectedArgsLength unit)
                   fnTy = fromMaybe Any (Map.lookup key aritiesMap)
                   expectedArgTys = extractAllArgTypes fnTy
                   retTy = extractFinalRetType fnTy
                   innerArgs = Array.mapWithIndex (\i eta -> boxUnbox currentMod (fromMaybe Any (Array.index expectedArgTys i)) Any (eta <> ".clone()")) etaArgs
                   innerCall = fullName <> "(" <> String.joinWith ", " innerArgs <> ")"
                   boxedInnerCall = boxUnbox currentMod Any retTy innerCall
               in (case Array.foldr (\etaArg (Tuple i code) -> 
                   let prevEtas = Array.take i etaArgs
                       clonesCode = String.joinWith " " (map (\prev -> "let mut " <> prev <> " = " <> prev <> ".clone();") prevEtas)
                   in Tuple (i - 1) ("crate::Value::Func(std::rc::Rc::new(move |mut " <> etaArg <> ": UnknownType| -> UnknownType { " <> clonesCode <> " " <> code <> " }))")
                 ) (Tuple (expectedArgsLength - 1) boxedInnerCall) etaArgs of
                 Tuple _ res -> boxUnbox currentMod fnTy Any res)
          else
            fullName
            
          isAlive = Set.member fullName alive
        in if isAlive then varCode <> ".clone()" else varCode
  Let mbId lvl val body ->
    let
      name = case mbId of
        Just (Ident nameRaw) -> sanitizeIdent nameRaw
        Nothing -> "lvl_" <> show (unwrap lvl)
      bodyVars = freeVariables body
      aliveForVal = Set.union alive bodyVars
      valCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForVal false val
      valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
      newBound = Map.insert name valTy bound
      -- if name is not in bodyVars, it's dead immediately
      deadCode = if Set.member name bodyVars then "" else "    drop(" <> name <> ");\n"
      newMbLoop = case mbLoop of
        Just l | l.name == name -> Nothing
        _ -> mbLoop
    in
      "{\n" <> 
      "    let mut " <> name <> " = " <> valCode <> ";\n" <>
      deadCode <>
      "    " <> codegenExpr_ currentMod allZeroArity allMacroBindings newMbLoop aritiesMap globalClassFields newBound alive inEffectBlock body <> "\n" <>
      "}"
  EffectBind mbIdent lvl val body ->
    let name = case mbIdent of
          Just (Ident n) -> sanitizeIdent n
          Nothing -> "lvl_" <> show (unwrap lvl)
        
        stripEffectDefer :: NeutralExpr -> NeutralExpr
        stripEffectDefer e@(NeutralExpr syn) = case syn of
          EffectDefer inner -> stripEffectDefer inner
          Abs _ inner -> stripEffectDefer inner
          UncurriedEffectAbs _ inner -> stripEffectDefer inner
          Let ident l v innerBody -> NeutralExpr (Let ident l v (stripEffectDefer innerBody))
          LetRec l bindings innerBody -> NeutralExpr (LetRec l bindings (stripEffectDefer innerBody))
          Typed ty inner -> NeutralExpr (Typed ty (stripEffectDefer inner))
          _ -> e
          
        realVal = stripEffectDefer val
        
        isUncurriedApp :: NeutralExpr -> Boolean
        isUncurriedApp (NeutralExpr syn) = case syn of
          UncurriedEffectApp _ _ -> true
          PrimEffect _ -> true
          EffectBind _ _ _ _ -> true
          Let _ _ _ innerBody -> isUncurriedApp innerBody
          LetRec _ _ innerBody -> isUncurriedApp innerBody
          Typed _ inner -> isUncurriedApp inner
          _ -> false
          
        aliveForVal = Set.union alive (freeVariables body)
        rawValCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForVal true realVal
        
        valCode = if isUncurriedApp realVal then rawValCode else 
          "{\n" <>
          "        let _val_eval = " <> rawValCode <> ";\n" <>
          "        if let crate::Value::Func(f) = &_val_eval {\n" <>
          "            f(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))\n" <>
          "        } else if let crate::Value::Record(r) = &_val_eval {\n" <>
          "            if r.call.is_some() {\n" <>
          "                r.call.clone().unwrap()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))\n" <>
          "            } else {\n" <>
          "                _val_eval\n" <>
          "            }\n" <>
          "        } else {\n" <>
          "            _val_eval\n" <>
          "        }\n" <>
          "    }"
        
        bodyVars = freeVariables body
        deadCode = if Set.member name bodyVars then "" else "    drop(" <> name <> ");\n"
        valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
        boundTy = case unwrapType valTy of
          ADT _ _ [t] -> t
          _ -> Any
        newBound = Map.insert name boundTy bound
        newMbLoop = case mbLoop of
          Just l | l.name == name -> Nothing
          _ -> mbLoop
        rawBodyCode = codegenExpr_ currentMod allZeroArity allMacroBindings newMbLoop aritiesMap globalClassFields newBound alive inEffectBlock body
        bodyCode = if isEffectNode body then rawBodyCode else
          "{\n" <>
          "        let _val_eval = " <> rawBodyCode <> ";\n" <>
          "        if let crate::Value::Func(f) = &_val_eval {\n" <>
          "            f(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))\n" <>
          "        } else if let crate::Value::Record(r) = &_val_eval {\n" <>
          "            if r.call.is_some() {\n" <>
          "                r.call.clone().unwrap()(crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() })))\n" <>
          "            } else {\n" <>
          "                _val_eval\n" <>
          "            }\n" <>
          "        } else {\n" <>
          "            _val_eval\n" <>
          "        }\n" <>
          "    }"
    in
    "{\n" <>
    "    let mut " <> name <> " = " <> boxUnbox currentMod boundTy Any valCode <> ";\n" <>
    deadCode <>
    "    " <> bodyCode <> "\n" <>
    "}"
  EffectPure val -> codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound alive false val
  Local mbId lvl -> 
    let name = case mbId of
          Just (Ident nameRaw) -> sanitizeIdent nameRaw
          Nothing -> "lvl_" <> show (unwrap lvl)
        t = case Map.lookup name bound of
          Just tVal -> tVal
          Nothing -> Any
        _ = if name == "sup" then Debug.trace ("LOCAL sup type is: " <> printType t) \_ -> unit else unit
    in if Set.member name alive then name <> ".clone()" else name
  Lit lit -> case lit of
    LitInt i -> show i
    LitNumber n -> show n
    LitString s -> "String::from(r#\"" <> s <> "\"#)"
    LitChar c -> show c
    LitBoolean b -> if b then "true" else "false"
    LitArray arr -> 
      let arrCode = Array.mapWithIndex (\i a -> 
            let subsequent = Array.drop (i + 1) arr
                aliveForA = Set.union alive (Array.foldl Set.union Set.empty (map freeVariables subsequent))
            in codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForA false a
          ) arr
      in "crate::mk_array(vec![" <> String.joinWith ", " arrCode <> "])"
    LitRecord props ->
      let arrProps = props
          fields = String.joinWith ", " (Array.mapWithIndex (\i (Prop k v) -> 
            let subsequent = Array.drop (i + 1) arrProps
                aliveForV = Set.union alive (Array.foldl Set.union Set.empty (map (\(Prop _ sv) -> freeVariables sv) subsequent))
                vCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForV false v
                vTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound v
                vFinal = boxUnbox currentMod Any vTy vCode
            in sanitizeIdent k <> ": Some(" <> vFinal <> ")"
          ) arrProps)
      in "crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { " <> fields <> (if Array.length props > 0 then ", " else "") <> "..Default::default() }))"
  Abs params body -> 
    let
      paramsArr = map (\(Tuple mbId lvl) -> case mbId of
        Just (Ident n) -> sanitizeIdent n
        Nothing -> "lvl_" <> show (unwrap lvl)) (NonEmptyArray.toArray params)
    in genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr Any body
  UncurriedAbs params body ->
    let
      paramsArr = map (\(Tuple mbId lvl) -> case mbId of
        Just (Ident n) -> sanitizeIdent n
        Nothing -> "lvl_" <> show (unwrap lvl)) params
    in genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr Any body
  UncurriedEffectAbs params body ->
    let
      paramsArr = map (\(Tuple mbId lvl) -> case mbId of
        Just (Ident n) -> sanitizeIdent n
        Nothing -> "lvl_" <> show (unwrap lvl)) params
    in genAbs currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive paramsArr Any body
  PrimUndefined -> "crate::Value::Record(perceus_ptr::PerceusPtr::new(crate::Record_a { ..Default::default() }))"
  CtorSaturated (Qualified mbMod _) _ (ProperName tyNameStr) (Ident ctorName) fields ->
    let
      modPrefix = getTyPrefix currentMod (Qualified mbMod (Ident tyNameStr))
      structKey = modPrefix <> sanitizeIdent tyNameStr
    in case Map.lookup structKey globalClassFields of
      Just classFields -> 
        let
          structName = case mbMod of
            Just (ModuleName mn) -> 
               let mnStr = String.replaceAll (Pattern ".") (Replacement "_") mn
               in if mnStr == currentMod then "crate::" <> sanitizeIdent tyNameStr else "Purs_" <> mnStr <> "::" <> sanitizeIdent tyNameStr
            Nothing -> "crate::" <> sanitizeIdent tyNameStr
          structFieldsCode = String.joinWith ", " (Array.mapWithIndex (\i (Tuple _ val) -> 
            let (Tuple fieldName expectedTy) = fromMaybe (Tuple ("field" <> show i) Any) (Array.index classFields i)
                subsequent = Array.drop (i + 1) fields
                aliveForV = Set.union alive (Array.foldl Set.union Set.empty (map (\(Tuple _ sv) -> freeVariables sv) subsequent))
                valCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForV false val
                valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
                resCode = boxUnbox currentMod expectedTy valTy valCode
                _ = if structName == "Purs_Data_Show::Show" then Debug.trace ("SHOW CtorSaturated field=" <> fieldName <> " expectedTy=" <> codegenExprType currentMod true expectedTy <> " valTy=" <> codegenExprType currentMod true valTy <> " valCode=" <> valCode <> " resCode=" <> resCode) \_ -> unit else unit
            in sanitizeIdent fieldName <> ": " <> resCode
          ) fields)
        in "std::rc::Rc::new(" <> structName <> " { " <> structFieldsCode <> " })"
      Nothing ->
        let
           enumPrefix = case mbMod of
             Just (ModuleName mn) -> 
                let mnStr = String.replaceAll (Pattern ".") (Replacement "_") mn
                in if mnStr == currentMod then "crate::" else "Purs_" <> mnStr <> "::"
             Nothing -> "crate::"
           enumName = sanitizeIdent tyNameStr
           ctorClean = sanitizeIdent ctorName
           
           fieldsCode = if Array.null fields then "" else 
               "(" <> String.joinWith ", " (Array.mapWithIndex (\i (Tuple _ val) -> 
                 let subsequent = Array.drop (i + 1) fields
                     aliveForV = Set.union alive (Array.foldl Set.union Set.empty (map (\(Tuple _ sv) -> freeVariables sv) subsequent))
                     valCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForV false val
                     valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
                     ctorFqn = (case mbMod of
                       Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
                       Nothing -> String.replaceAll (Pattern ".") (Replacement "_") currentMod <> "_") <> ctorName
                     expectedFieldTy = case Map.lookup ctorFqn aritiesMap of
                       Just ctorTy -> fromMaybe Any (Array.index (extractAllArgTypes ctorTy) i)
                       Nothing -> Any
                 in boxUnbox currentMod expectedFieldTy valTy valCode
               ) fields) <> ")"
        in "std::rc::Rc::new(" <> enumPrefix <> enumName <> "::" <> ctorClean <> fieldsCode <> ")"
  CtorDef _ (ProperName tyNameStr) (Ident ctorName) fields -> 
      let enumPrefix = if currentMod == tyNameStr then "crate::" else "Purs_" <> currentMod <> "::" 
          rustCtor = "crate::" <> sanitizeIdent tyNameStr <> "::" <> sanitizeIdent ctorName
          len = Array.length fields
          ctorTy = fromMaybe Any (Map.lookup (currentMod <> "_" <> sanitizeIdent ctorName) aritiesMap)
          argTys = extractAllArgTypes ctorTy
          retTy = extractFinalRetType ctorTy
          retTyStr = codegenExprType currentMod true retTy
          genCurried 0 args = "std::rc::Rc::new(" <> rustCtor <> "(" <> String.joinWith ", " (map (\a -> a <> ".clone()") args) <> "))"
          genCurried n args = 
            let argName = "a" <> show (len - n)
                argTy = fromMaybe Any (Array.index argTys (len - n))
                argTyStr = codegenExprType currentMod false argTy
                nextRetTyStr = if n == 1 then retTyStr else "std::rc::Rc<dyn Fn(" <> codegenExprType currentMod false (fromMaybe Any (Array.index argTys (len - n + 1))) <> ") -> " <> codegenExprType currentMod true (if n > 2 then Func (Array.drop (len - n + 2) argTys) retTy else if n == 2 then retTy else Any) <> ">"
                clonesCode = if n > 1 && Array.length args > 0 then String.joinWith " " (map (\a -> "let mut " <> a <> " = " <> a <> ".clone();") args) <> " " else ""
            in "std::rc::Rc::new(move |mut " <> argName <> ": " <> argTyStr <> "| -> " <> nextRetTyStr <> " { " <> clonesCode <> genCurried (n - 1) (Array.snoc args argName) <> " })"
      in if len == 0 then "std::rc::Rc::new(" <> rustCtor <> ")" else genCurried len []

  LetRec _ binds body ->
    let
      bindsArray = NonEmptyArray.toArray binds
      
      declCode = String.joinWith "\n    " (map (\(Tuple (Ident n) _) -> 
          "let mut " <> sanitizeIdent n <> " = crate::Value::Record(perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }));"
        ) bindsArray)
      
      evalCode = String.joinWith "\n    " (Array.mapWithIndex (\i (Tuple (Ident n) val) -> 
          let clonesCode = String.joinWith "\n        " (map (\(Tuple (Ident cn) _) -> 
                  "let mut " <> sanitizeIdent cn <> " = " <> sanitizeIdent cn <> ".clone();"
                ) bindsArray)
              subsequentVals = Array.drop (i + 1) bindsArray
              varsSubsequent = Array.foldl (\acc (Tuple _ v) -> Set.union acc (freeVariables v)) Set.empty subsequentVals
              bindsVarsForAlive = Array.foldl (\acc (Tuple (Ident bn) _) -> Set.insert (sanitizeIdent bn) acc) Set.empty bindsArray
              aliveForVal = Set.union alive (Set.union bindsVarsForAlive (Set.union (freeVariables body) varsSubsequent))
              
              valTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound val
              allArgTypes = extractAllArgTypes valTy
              retType = extractFinalRetType valTy
              extracted = extractAbsParams (Array.length allArgTypes) val
              isSelfRecursive = Set.member (sanitizeIdent n) (freeVariables val)
              isTCO = isSelfRecursive && (case extracted of
                Just _ -> true
                Nothing -> false)
                
          in if isTCO && Array.length allArgTypes > 0 then
               let paramsArr = case extracted of
                     Just (Tuple p _) -> p
                     Nothing -> []
                   dedupedParams = dedupArgs paramsArr
                   innerExpr = case extracted of
                     Just (Tuple _ inner) -> inner
                     Nothing -> val
                     
                   capturedSet = Set.difference (freeVariables val) (Set.fromFoldable dedupedParams)
                   capturedArr = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity)) (Array.fromFoldable capturedSet)
                   
                   -- Inner function definition
                   fnName = sanitizeIdent n <> "_impl"
                   capturedArgs = map (\c -> "mut " <> sanitizeIdent c <> ": " <> codegenExprType currentMod false (fromMaybe Any (Map.lookup c bound))) capturedArr
                   paramPairs = Array.zip dedupedParams allArgTypes
                   funcArgs = map (\(Tuple p ty) -> "mut " <> sanitizeIdent p <> ": " <> codegenExprType currentMod false ty) paramPairs
                   allArgsCode = String.joinWith ", " (capturedArgs <> funcArgs)
                   
                   mbLoop = Just { name: sanitizeIdent n, params: dedupedParams }
                   innerBound = Array.foldl (\b (Tuple p ty) -> Map.insert (sanitizeIdent p) ty b) bound paramPairs
                   bodyRaw = codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields innerBound (freeVariables innerExpr) false innerExpr
                   bodyTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields innerBound innerExpr
                   boxedBody = boxUnbox currentMod retType bodyTy bodyRaw
                   
                   fnCode = "fn " <> fnName <> "(" <> allArgsCode <> ") -> " <> codegenExprType currentMod true retType <> " {\n        loop {\n            break " <> boxedBody <> ";\n        }\n    }"
                   
                   -- Bridge closure
                   bridgeCode = Array.foldr (\(Tuple j (Tuple p ty)) st -> 
                        let pTyStr = codegenExprType currentMod false ty
                            capturedForThis = capturedArr <> Array.take j dedupedParams
                            clones = String.joinWith "\n        " (map (\c -> "let mut " <> sanitizeIdent c <> " = " <> sanitizeIdent c <> ".clone();") capturedForThis)
                            innerCall = if j == (Array.length paramPairs - 1) then
                                            let innerArgs = String.joinWith ", " (map sanitizeIdent capturedArr <> map sanitizeIdent dedupedParams)
                                            in fnName <> "(" <> innerArgs <> ")"
                                        else st
                            remainingArgTys = Array.drop (j + 1) (map (\(Tuple _ t) -> t) paramPairs)
                            thisRetTy = if Array.length remainingArgTys > 0 then Func remainingArgTys retType else retType
                            retTyStr = codegenExprType currentMod true thisRetTy
                        in "std::rc::Rc::new(move |mut " <> sanitizeIdent p <> ": " <> pTyStr <> "| -> " <> retTyStr <> " {\n        " <> clones <> "\n        " <> innerCall <> "\n    })"
                      ) "" (Array.mapWithIndex Tuple paramPairs)
                     
                   finalBridgeCode = boxUnbox currentMod Any valTy bridgeCode
                   capturedClones = String.joinWith "\n        " (map (\c -> "let mut " <> sanitizeIdent c <> " = " <> sanitizeIdent c <> ".clone();") capturedArr)
               in "let val_" <> sanitizeIdent n <> " = {\n        " <> clonesCode <> "\n        " <> capturedClones <> "\n        " <> fnCode <> "\n        " <> finalBridgeCode <> "\n    };"
             else
               let valCode = codegenExpr_ currentMod allZeroArity allMacroBindings Nothing aritiesMap globalClassFields bound aliveForVal false val
                   boxedValCode = boxUnbox currentMod Any valTy valCode
               in "let val_" <> sanitizeIdent n <> " = {\n        " <> clonesCode <> "\n        " <> boxedValCode <> "\n    };"
        ) bindsArray)
        
      mutCode = String.joinWith "\n    " (map (\(Tuple (Ident n) _) -> 
          "*(unsafe { perceus_ptr::PerceusPtr::force_mut(" <> sanitizeIdent n <> ".as_record_mut()) }) = crate::Record_a { call: Some((val_" <> sanitizeIdent n <> ").unwrap_func()), ..Default::default() };"
        ) bindsArray)
        
      newMbLoop = case mbLoop of
        Just l | Array.any (\(Tuple (Ident n) _) -> sanitizeIdent n == l.name) bindsArray -> Nothing
        _ -> mbLoop
      bodyCode = codegenExpr_ currentMod allZeroArity allMacroBindings newMbLoop aritiesMap globalClassFields bound alive inEffectBlock body
    in "{\n    " <> declCode <> "\n    " <> evalCode <> "\n    " <> mutCode <> "\n    " <> bodyCode <> "\n}"

  EffectDefer inner -> codegenExpr_ currentMod allZeroArity allMacroBindings mbLoop aritiesMap globalClassFields bound alive inEffectBlock inner
  Fail _ -> "unimplemented!() /* Unsupported Expr: Fail */"
  _ -> "{ let _t: crate::UnknownType = unimplemented!(); _t } /* Unsupported Expr: " <> printAST expr <> " */"

printAST :: NeutralExpr -> String
printAST (NeutralExpr expr) = case expr of
  App fn _ -> "App(" <> printAST fn <> ")"
  Lit _ -> "Lit"
  Var _ -> "Var(...)"
  Let _ _ _ _ -> "Let(...)"
  Local _ _ -> "Local(...)"
  Abs _ inner -> "Abs(..., " <> printAST inner <> ")"
  Typed _ inner -> "Typed(" <> printAST inner <> ")"
  EffectBind _ _ _ _ -> "EffectBind"
  EffectPure _ -> "EffectPure"
  Update _ _ -> "Update"
  Accessor inner prop -> "Accessor(" <> printAST inner <> ")"
  UncurriedEffectApp fn _ -> "UncurriedEffectApp(" <> printAST fn <> ")"
  LetRec _ _ inner -> "LetRec(..., " <> printAST inner <> ")"
  Branch _ _ -> "Branch(...)"
  PrimOp _ -> "PrimOp(...)"
  UncurriedApp fn _ -> "UncurriedApp(" <> printAST fn <> ")"
  CtorSaturated _ _ _ _ _ -> "CtorSaturated(...)"
  UncurriedAbs _ inner -> "UncurriedAbs(..., " <> printAST inner <> ")"
  UncurriedEffectAbs _ inner -> "UncurriedEffectAbs(..., " <> printAST inner <> ")"
  CtorDef _ _ _ _ -> "CtorDef"
  EffectDefer inner -> "EffectDefer(" <> printAST inner <> ")"
  PrimEffect _ -> "PrimEffect(...)"
  PrimUndefined -> "PrimUndefined"
  Fail msg -> "Fail(" <> msg <> ")"

freeVariables :: NeutralExpr -> Set String
freeVariables (NeutralExpr expr) = case expr of
  Var (Qualified mbMod (Ident name)) -> 
    let modPrefix = case mbMod of
          Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
          Nothing -> ""
    in Set.singleton (modPrefix <> sanitizeIdent name)
  Local mbId lvl -> Set.singleton (case mbId of
      Just (Ident nameRaw) -> sanitizeIdent nameRaw
      Nothing -> "lvl_" <> show (unwrap lvl))
  App fn args -> 
    Array.foldl (\acc a -> Set.union acc (freeVariables a)) (freeVariables fn) (NonEmptyArray.toArray args)
  Let mbId lvl val body ->
    let name = case mbId of
          Just (Ident i) -> sanitizeIdent i
          Nothing -> "lvl_" <> show (unwrap lvl)
    in Set.union (freeVariables val) (Set.delete name (freeVariables body))
  Typed _ inner -> freeVariables inner
  Update base props ->
    Array.foldl (\acc (Prop _ v) -> Set.union acc (freeVariables v)) (freeVariables base) props
  Branch branches def ->
    let branchVars = Array.foldl (\acc (Pair cond body) -> Set.union acc (Set.union (freeVariables cond) (freeVariables body))) Set.empty (NonEmptyArray.toArray branches)
    in Set.union branchVars (freeVariables def)
  PrimOp (Op1 _ a) -> freeVariables a
  PrimOp (Op2 _ a b) -> Set.union (freeVariables a) (freeVariables b)
  Accessor base _ -> freeVariables base
  EffectBind mbIdent lvl val body ->
    let name = case mbIdent of
          Just (Ident i) -> sanitizeIdent i
          Nothing -> "lvl_" <> show (unwrap lvl)
        bodyVars = Set.delete name (freeVariables body)
    in Set.union (freeVariables val) bodyVars
  EffectPure val -> freeVariables val
  LetRec _ binds body ->
    let bindsVars = Array.foldl (\acc (Tuple (Ident n) _) -> Set.insert (sanitizeIdent n) acc) Set.empty (NonEmptyArray.toArray binds)
        allValsVars = Array.foldl (\acc (Tuple _ v) -> Set.union acc (freeVariables v)) Set.empty (NonEmptyArray.toArray binds)
    in Set.difference (Set.union allValsVars (freeVariables body)) bindsVars
  Abs params body ->
    let paramsVars = Array.foldl (\acc (Tuple mbId lvl) -> case mbId of
          Just (Ident n) -> Set.insert (sanitizeIdent n) acc
          Nothing -> Set.insert ("lvl_" <> show (unwrap lvl)) acc) Set.empty (NonEmptyArray.toArray params)
    in Set.difference (freeVariables body) paramsVars
  UncurriedAbs params body ->
    let paramsVars = Array.foldl (\acc (Tuple mbId lvl) -> case mbId of
          Just (Ident n) -> Set.insert (sanitizeIdent n) acc
          Nothing -> Set.insert ("lvl_" <> show (unwrap lvl)) acc) Set.empty params
    in Set.difference (freeVariables body) paramsVars
  UncurriedEffectAbs params body ->
    let paramsVars = Array.foldl (\acc (Tuple mbId lvl) -> case mbId of
          Just (Ident n) -> Set.insert (sanitizeIdent n) acc
          Nothing -> Set.insert ("lvl_" <> show (unwrap lvl)) acc) Set.empty params
    in Set.difference (freeVariables body) paramsVars
  UncurriedApp fn args ->
    Array.foldl (\acc a -> Set.union acc (freeVariables a)) (freeVariables fn) args
  UncurriedEffectApp fn args ->
    Array.foldl (\acc a -> Set.union acc (freeVariables a)) (freeVariables fn) args
  Fail _ -> Set.empty
  EffectDefer inner -> freeVariables inner
  Lit (LitArray arr) -> Array.foldl (\acc a -> Set.union acc (freeVariables a)) Set.empty arr
  Lit (LitRecord props) -> Array.foldl (\acc (Prop _ v) -> Set.union acc (freeVariables v)) Set.empty props
  CtorSaturated _ _ _ _ fields -> Array.foldl (\acc (Tuple _ v) -> Set.union acc (freeVariables v)) Set.empty fields
  _ -> Set.empty

inferTypeExprGlobal :: String -> Map.Map String ExprType -> Map.Map String (Array (Tuple String ExprType)) -> Map.Map String ExprType -> NeutralExpr -> ExprType
inferTypeExprGlobal currentMod aritiesMap globalClassFields bound (NeutralExpr expr) = case expr of
  Accessor base (GetProp k) -> 
    let baseTy = inferTypeExprGlobal currentMod aritiesMap globalClassFields bound base
        findFieldTy (ADT _ fqn _) =
          let modStr = String.joinWith "_" (Array.dropEnd 1 fqn)
              nameStr = fromMaybe "" (Array.last fqn)
          in case Map.lookup (modStr <> "_" <> nameStr) globalClassFields of
               Just classFields -> case Array.find (\(Tuple fn _) -> fn == sanitizeIdent k) classFields of
                 Just (Tuple _ t) -> t
                 Nothing -> Any
               Nothing -> Any
        findFieldTy _ = Any
    in findFieldTy (unwrapType baseTy)
  Accessor _ (GetCtorField (Qualified mbMod _) _ _ (Ident ctorName) _ fieldIdx) ->
    let modStr = case mbMod of
          Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn
          Nothing -> currentMod
        ctorFqn = modStr <> "_" <> sanitizeIdent ctorName
    in case Map.lookup ctorFqn aritiesMap of
         Just ctorTy -> 
           let args = extractAllArgTypes ctorTy
           in case Array.index args fieldIdx of
             Just t -> t
             Nothing -> Debug.trace ("Warning: fieldIdx " <> show fieldIdx <> " out of bounds for " <> ctorFqn <> " (args len: " <> show (Array.length args) <> ")") \_ -> Any
         Nothing -> Debug.trace ("Warning: ctorFqn not found in aritiesMap: " <> ctorFqn) \_ -> Any
  _ -> inferTypeExpr currentMod aritiesMap bound (NeutralExpr expr)

inferTypeExpr :: String -> Map.Map String ExprType -> Map.Map String ExprType -> NeutralExpr -> ExprType
inferTypeExpr currentMod aritiesMap bound (NeutralExpr expr) = case expr of


  App fn args -> 
    let stripTyped (NeutralExpr (Typed _ i)) = stripTyped i
        stripTyped other = other
    in case stripTyped fn of
      NeutralExpr (Var (Qualified _ (Ident "not"))) -> Boolean
      NeutralExpr (Var (Qualified (Just (ModuleName "Data.HeytingAlgebra")) (Ident "not"))) -> Boolean
      _ -> case unwrapType (inferTypeExpr currentMod aritiesMap bound fn) of
        Func argTypes retTy -> 
          let expectedCount = Array.length argTypes
              providedCount = NonEmptyArray.length args
          in if expectedCount > providedCount then
               Func (Array.drop providedCount argTypes) retTy
             else retTy
        _ -> Any


  UncurriedApp fn _args -> 
    case unwrapType (inferTypeExpr currentMod aritiesMap bound fn) of
      Func _ retTy -> retTy
      _ -> Any
  UncurriedEffectApp fn args -> 
    case unwrapType (inferTypeExpr currentMod aritiesMap bound fn) of
      Func _ retTy -> retTy
      _ -> Any
  Abs _ _ -> Func [Any] Any
  UncurriedAbs params _ -> Func (map (\_ -> Any) params) Any
  UncurriedEffectAbs params _ -> Func (map (\_ -> Any) params) Any
  LetRec _ _ inner -> inferTypeExpr currentMod aritiesMap bound inner
  EffectBind _ _ _ inner -> inferTypeExpr currentMod aritiesMap bound inner
  EffectPure inner -> inferTypeExpr currentMod aritiesMap bound inner
  EffectDefer inner -> inferTypeExpr currentMod aritiesMap bound inner
  Branch branches def ->
    let defTy = inferTypeExpr currentMod aritiesMap bound def
    in case defTy of
      Any -> 
        let Pair _ body = NonEmptyArray.head branches
        in inferTypeExpr currentMod aritiesMap bound body
      _ -> defTy
  Typed ty inner ->
    let innerTy = inferTypeExpr currentMod aritiesMap bound inner
    in case unwrapType ty, unwrapType innerTy of
      Any, _ -> innerTy
      _, Any -> ty
      Func _ _, Boolean -> innerTy
      Func _ _, Int -> innerTy
      Func _ _, Number -> innerTy
      Func _ _, String -> innerTy
      Func _ _, Char -> innerTy
      Func _ _, ADT _ _ _ -> innerTy
      _, _ -> ty
  CtorSaturated (Qualified mbMod _) _ (ProperName tyNameStr) _ _ -> 
    let modStr = case mbMod of
          Just (ModuleName mn) -> mn
          Nothing -> currentMod
    in ADT modStr [modStr, tyNameStr] []
  CtorDef _ (ProperName tyNameStr) (Ident ctorName) _ -> fromMaybe Any (Map.lookup (currentMod <> "_" <> sanitizeIdent ctorName) aritiesMap)
  Var (Qualified mbMod (Ident name)) -> 
    let sName = sanitizeIdent name
    in case Map.lookup sName bound of
      Just ty -> ty
      Nothing -> 
        let modPrefix = case mbMod of
              Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
              Nothing -> String.replaceAll (Pattern ".") (Replacement "_") currentMod <> "_"
            fullName = modPrefix <> sName
        in case Map.lookup fullName aritiesMap of
          Just ty -> ty
          Nothing -> Any
  Local mbName lvl ->
    let name = case mbName of
          Just (Ident n) -> sanitizeIdent n
          Nothing -> "lvl_" <> show (unwrap lvl)
    in case Map.lookup name bound of
      Just ty -> ty
      Nothing -> Any
  Let (Just (Ident i)) _ val body -> inferTypeExpr currentMod aritiesMap (Map.insert (sanitizeIdent i) (inferTypeExpr currentMod aritiesMap bound val) bound) body
  Let Nothing _ _ inner -> inferTypeExpr currentMod aritiesMap bound inner

  PrimOp (Op1 op _) -> case op of
    OpBooleanNot -> Boolean
    OpIntBitNot -> Int
    OpIntNegate -> Int
    OpNumberNegate -> Number
    OpArrayLength -> Int
    OpIsTag _ -> Boolean
    _ -> Any
  PrimOp (Op2 op _ _) -> case op of
    OpIntNum _ -> Int
    OpNumberNum _ -> Number
    OpBooleanAnd -> Boolean
    OpBooleanOr -> Boolean
    OpBooleanOrd _ -> Boolean
    OpIntOrd _ -> Boolean
    OpNumberOrd _ -> Boolean
    OpStringOrd _ -> Boolean
    OpCharOrd _ -> Boolean
    OpStringAppend -> String
    _ -> Any
  Lit lit -> case lit of
    LitInt _ -> Int
    LitNumber _ -> Number
    LitString _ -> String
    LitChar _ -> Char
    LitBoolean _ -> Boolean
    _ -> Any
  _ -> Any

getArity :: ExprType -> Int
getArity (ForAll _ t) = getArity t
getArity (ConstrainedType cs t) = Array.length cs + getArity t
getArity (Func args t) = Array.length args + getArity t
getArity _ = 0



sanitizeIdent :: String -> String
sanitizeIdent s = 
  let s1 = String.replaceAll (Pattern "'") (Replacement "_prime") s
      s2 = String.replaceAll (Pattern "$") (Replacement "_dollar_") s1
      s3 = String.replaceAll (Pattern "-") (Replacement "_minus_") s2
      s4 = String.replaceAll (Pattern ".") (Replacement "_dot_") s3
  in if s4 == "type" then "type_kw" 
     else if s4 == "fn" then "fn_kw" 
     else if s4 == "break" then "break_kw"
     else if s4 == "mod" then "mod_kw"
     else if s4 == "as" then "as_kw"
     else if s4 == "gen" then "gen_kw"
     else if s4 == "use" then "use_kw"
     else if s4 == "pub" then "pub_kw"
     else if s4 == "ref" then "ref_kw"
     else if s4 == "mut" then "mut_kw"
     else if s4 == "move" then "move_kw"
     else if s4 == "let" then "let_kw"
     else if s4 == "if" then "if_kw"
     else if s4 == "loop" then "loop_kw"
     else s4

dedupArgs :: Array String -> Array String
dedupArgs arr =
  let
    step acc item =
      let count = Map.lookup item acc.counts
      in case count of
        Nothing ->
          { result: Array.snoc acc.result item, counts: Map.insert item 1 acc.counts }
        Just c ->
          let newItem = item <> "_" <> show c
          in { result: Array.snoc acc.result newItem, counts: Map.insert item (c + 1) acc.counts }
  in (Array.foldl step { result: [], counts: Map.empty } arr).result
