module Purust.CodeGen where

import Prelude
import PureScript.Backend.Optimizer.Syntax (BackendSyntax(..), BackendAccessor(..), BackendOperator(..), BackendOperator1(..), BackendOperator2(..), BackendOperatorNum(..), BackendOperatorOrd(..), Pair(..))
import PureScript.Backend.Optimizer.Convert (BackendModule, BackendBindingGroup)
import PureScript.Backend.Optimizer.Semantics (NeutralExpr(..))
import PureScript.Backend.Optimizer.CoreFn (Ann(..), Module(..), Ident(..), ExprType(..), DataDecl, Literal(..), Qualified(..), ModuleName(..), Prop(..), ProperName(..))
import Data.String as String
import Data.Array as Array
import Data.Array.NonEmpty as NonEmptyArray
import Data.Foldable (foldMap)
import Data.Newtype (unwrap)
import Data.Maybe (Maybe(..))
import Data.Tuple (Tuple(..))
import Data.Set (Set)
import Data.Set as Set
import Data.Map (Map)
import Data.Map as Map
import Data.String.Pattern (Pattern(..), Replacement(..))
import Data.Maybe (Maybe(..), fromMaybe)
import Partial.Unsafe (unsafeCrashWith)

codegenModule :: Module Ann -> BackendModule -> String
codegenModule (Module coreFnMod) backendMod =
  let
    modNameStr = unwrap backendMod.name
    
    -- Traduction des DataDecls
    dataDeclsCode = foldMap (\(decl :: DataDecl) ->
        "// Enum for ADT: " <> decl.typeName <> "\n" <>
        "#[derive(Clone)]\npub enum " <> decl.typeName <> " {\n" <>
        foldMap (\ctor -> 
          let fields = if Array.null ctor.fieldTypes then "" 
                       else "(" <> String.joinWith ", " (map (codegenExprType true) ctor.fieldTypes) <> ")"
          in "    " <> ctor.constructorName <> fields <> ",\n"
        ) decl.constructors <>
        "}\n\n"
      ) backendMod.dataDecls <>
      "#[derive(Clone)]\npub struct Record_a {\n" <>
      "    pub a: i64,\n" <>
      "    pub b: Option<UnknownType>,\n" <>
      "    pub c: Option<UnknownType>,\n" <>
      "    pub ccc: Option<UnknownType>,\n" <>
      "    pub d: Option<UnknownType>,\n" <>
      "    pub x: Option<UnknownType>,\n" <>
      "    pub Applicative0: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub pure: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub discard: Option<std::rc::Rc<dyn Fn(UnknownType, UnknownType, UnknownType) -> UnknownType>>,\n" <>
      "    pub show: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "}\n\n"
      
    -- Traduction des Bindings
    bindingsRes = Array.foldl (\acc group -> 
      let res = codegenBindingGroup modNameStr Set.empty Set.empty acc.arities group
      in { code: acc.code <> res.code, arities: res.arities }
    ) { code: "", arities: Map.empty } backendMod.bindings
    
    bindingsCode = bindingsRes.code
    
  in
    "#![allow(warnings)]\n" <>
    "// Code generated by purust for module " <> modNameStr <> "\n\n" <>
    "use perceus_ptr::PerceusPtr;\n\n" <>
    "pub type UnknownType = perceus_ptr::PerceusPtr<Record_a>;\n\n" <>
    "pub fn unsafe_coerce<T>(_: T) -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { a: 0, b: None, c: None, ccc: None, d: None, x: None, Applicative0: None, pure: None, show: None, discard: None }) }\n\n" <>
    "pub fn mk_int(val: i64) -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { a: val, b: None, c: None, ccc: None, d: None, x: None, Applicative0: None, pure: None, show: None, discard: None }) }\n\n" <>
    "pub fn Effect_Console_log<T>(_: T) -> UnknownType { unsafe_coerce(0) }\n\n" <>
    "pub fn Control_Bind_discardUnit() -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { a: 0, b: None, c: None, ccc: None, d: None, x: None, Applicative0: None, pure: None, show: None, discard: Some(std::rc::Rc::new(move |_, _, cont| { cont })) }) }\n" <>
    "pub fn Effect_bindEffect() -> UnknownType { unsafe_coerce(0) }\n" <>
    "pub fn Data_Show_showString() -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { a: 0, b: None, c: None, ccc: None, d: None, x: None, Applicative0: None, pure: None, discard: None, show: Some(std::rc::Rc::new(move |_| { unsafe_coerce(0) })) }) }\n\n" <>
    "// Data declarations:\n" <>
    dataDeclsCode <>
    "// Bindings:\n" <>
    bindingsCode
    
codegenExprType :: Boolean -> ExprType -> String
codegenExprType isRet = case _ of
  Func args ret -> "std::rc::Rc<dyn Fn(" <> String.joinWith ", " (map (codegenExprType false) args) <> ") -> " <> codegenExprType true ret <> ">"
  Any -> "UnknownType"
  Record _ -> "UnknownType"
  Array _ -> "UnknownType"
  String -> "UnknownType"
  Int -> "UnknownType"
  Number -> "UnknownType"
  Boolean -> "bool"
  Char -> "UnknownType"
  Record _ -> "UnknownType"
  ADT name _ | Array.last name == Just "Boolean" -> "bool"
  ADT name _ -> Array.last name # fromMaybe "UnknownType"
  TypeVar _ -> "UnknownType"
  _ -> "UnknownType"

codegenBindingGroup :: String -> Set.Set String -> Set.Set String -> Map.Map String ExprType -> BackendBindingGroup Ident NeutralExpr -> { code :: String, arities :: Map.Map String ExprType }
codegenBindingGroup modNameStr allZeroArity allMacroBindings aritiesMap group =
  let
    isSelfRecursive = group.recursive && Array.length group.bindings == 1
    
    groupArities = Map.fromFoldable $ map (\(Tuple ident expr) -> 
        let rawIdentName = case ident of
              Ident i -> sanitizeIdent i
              _ -> "unknown"
            identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
            inferredTy = inferTypeExpr modNameStr aritiesMap Map.empty expr
        in Tuple identName inferredTy
      ) group.bindings
      
    mergedArities = Map.union groupArities aritiesMap
    
    code = foldMap (\(Tuple ident expr) ->
      let
        rawIdentName = case ident of
          Ident i -> sanitizeIdent i
          _ -> "unknown"
        identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
        inferredType = fromMaybe Any (Map.lookup identName groupArities)
        innerExpr = case expr of
           NeutralExpr (Typed _ inner) -> inner
           NeutralExpr inner -> NeutralExpr inner
           _ -> expr
        { paramsCode, retCode, bodyCode, isFunc } = case inferredType of
          Func argTypes retType ->
            let
              paramsArr = case innerExpr of
                NeutralExpr (Abs params _) -> map (\(Tuple mbId _) -> case mbId of
                  Just (Ident n) -> n
                  _ -> "_") (NonEmptyArray.toArray params)
                _ -> Array.mapWithIndex (\i _ -> "a" <> show i) argTypes
              deduped = dedupArgs paramsArr
              mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
              paramPairs = Array.zip deduped argTypes
              pCode = String.joinWith ", " $ map (\(Tuple pName ty) ->
                let p = sanitizeIdent pName in
                (if p == "_" then "" else "mut ") <> p <> ": " <> codegenExprType true ty) paramPairs
              bound = Map.fromFoldable (map (\(Tuple k v) -> Tuple (if k == "_" then "_" else k) v) paramPairs)
              bodyCodeRaw = case innerExpr of
                NeutralExpr (Abs _ body) -> codegenExpr modNameStr allZeroArity allMacroBindings mbLoop (Map.union bound aritiesMap) body
                _ -> 
                   let fnCode = codegenExpr modNameStr allZeroArity allMacroBindings mbLoop (Map.union bound aritiesMap) innerExpr
                       argsCode = String.joinWith ", " (map (\p -> sanitizeIdent p <> ".clone()") deduped)
                   in "(" <> fnCode <> ")(" <> argsCode <> ")"
            in { paramsCode: pCode, retCode: codegenExprType true retType, bodyCode: bodyCodeRaw, isFunc: true }
          _ -> 
            let isAbs = case innerExpr of
                  NeutralExpr (Abs _ _) -> true
                  _ -> false
            in if isAbs then
              let
                params = case innerExpr of
                  NeutralExpr (Abs p _) -> p
                  _ -> unsafeCrashWith "impossible"
                paramsArr = map (\(Tuple mbId _) -> case mbId of
                  Just (Ident n) -> n
                  _ -> "_") (NonEmptyArray.toArray params)
                deduped = dedupArgs paramsArr
                mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
                pCode = String.joinWith ", " $ map (\pName ->
                  let p = sanitizeIdent pName in
                  (if p == "_" then "" else "mut ") <> p <> ": UnknownType") deduped
                bound = Map.empty
                body = case innerExpr of
                  NeutralExpr (Abs _ b) -> b
                  _ -> unsafeCrashWith "impossible"
              in { paramsCode: pCode, retCode: "UnknownType", bodyCode: codegenExpr modNameStr allZeroArity allMacroBindings mbLoop (Map.union bound aritiesMap) body, isFunc: true }
            else
              { paramsCode: "", retCode: codegenExprType true inferredType, bodyCode: codegenExpr modNameStr allZeroArity allMacroBindings Nothing aritiesMap expr, isFunc: false }
        
        bodyCodeWithLoop = if isSelfRecursive && isFunc then
            "    let mut _tco_loop = true;\n" <>
            "    while _tco_loop {\n" <>
            "        _tco_loop = false;\n" <>
            "        " <> bodyCode <> "\n" <>
            "    }"
          else bodyCode
          
        bodyCodeFinal = bodyCodeWithLoop
      in
        if identName == "main" then
          "pub fn main() {\n" <>
          "    // AST: " <> printAST expr <> "\n" <>
          "    " <> bodyCodeFinal <> ";\n" <>
          "}\n\n"
        else
          "pub fn " <> identName <> "(" <> paramsCode <> ")" <> (if retCode == "" then "" else " -> " <> retCode) <> " {\n" <>
          "    // AST: " <> printAST expr <> "\n" <>
          bodyCodeFinal <> "\n" <>
          "}\n\n"
    ) group.bindings
  in { code: code, arities: mergedArities }

codegenExpr :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> NeutralExpr -> String
codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound (NeutralExpr expr) = case expr of
  Typed _ inner -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound inner

  App fn args -> 
    let fnCode = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound fn
        argsCodeArray = map (codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound) (NonEmptyArray.toArray args)
        argsCode = String.joinWith ", " argsCodeArray
        
        fnTy = inferTypeExpr currentMod bound bound fn
        fnArity = case fnTy of
          Func a _ -> Array.length a
          _ -> 0
        
        numProvided = Array.length (NonEmptyArray.toArray args)
    in if fnArity > numProvided then
         let numMissing = fnArity - numProvided
             missingVars = Array.mapWithIndex (\i _ -> "c_" <> show i) (Array.replicate numMissing unit)
             missingArgs = String.joinWith ", " (map (\v -> "mut " <> v <> ": UnknownType") missingVars)
             closureArgs = String.joinWith ", " (argsCodeArray <> map (\v -> v <> ".clone()") missingVars)
         in "std::rc::Rc::new(move |" <> missingArgs <> "| (" <> fnCode <> ")(" <> closureArgs <> "))"
       else
         "(" <> fnCode <> ")(" <> argsCode <> ")"

  UncurriedEffectApp fn args -> 
    case fn of
      NeutralExpr (Typed _ (NeutralExpr (Accessor _ (GetProp "logRecord")))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Accessor _ (GetProp "logRecord")) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Typed _ (NeutralExpr (Var (Qualified _ (Ident "logRecord"))))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Var (Qualified _ (Ident "logRecord"))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      _ -> "// Unsupported UncurriedEffectApp with fn: " <> printAST fn <> "\n"

  Update base props ->
    let
      propsCode = map (\(Prop k v) -> "_mut." <> k <> " = " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound v <> ";") props
    in
      "{\n" <>
      "    let mut _base = " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound base <> ";\n" <>
      "    {\n" <>
      "        let _mut = perceus_ptr::PerceusPtr::make_mut(&mut _base);\n" <>
      "        " <> String.joinWith "\n        " propsCode <> "\n" <>
      "    }\n" <>
      "    _base\n" <>
      "}"
  Branch branches def ->
    let
      branchCode = map (\(Pair cond body) -> 
        "if " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound cond <> " {\n        " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n    }") (NonEmptyArray.toArray branches)
      defCode = "{\n        " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound def <> "\n    }"
    in
      String.joinWith " else " branchCode <> " else " <> defCode
  PrimOp (Op1 op a) ->
    let aStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a
    in case op of
      OpBooleanNot -> "!" <> aStr
      OpIntNegate -> "-" <> aStr
      OpNumberNegate -> "-" <> aStr
      _ -> "// Unsupported Op1"
  PrimOp (Op2 op a b) ->
    let aStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound a
        bStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound b
    in case op of
      OpIntNum OpAdd -> "mk_int((" <> aStr <> ").a + (" <> bStr <> ").a)"
      OpIntNum OpSubtract -> "mk_int((" <> aStr <> ").a - (" <> bStr <> ").a)"
      OpIntNum OpMultiply -> "mk_int((" <> aStr <> ").a * (" <> bStr <> ").a)"
      OpIntNum OpDivide -> "mk_int((" <> aStr <> ").a / (" <> bStr <> ").a)"
      OpIntOrd OpEq -> "((" <> aStr <> ").a == (" <> bStr <> ").a)"
      OpIntOrd OpNotEq -> "(" <> aStr <> " != " <> bStr <> ")"
      OpIntOrd OpGt -> "(" <> aStr <> " > " <> bStr <> ")"
      OpIntOrd OpGte -> "(" <> aStr <> " >= " <> bStr <> ")"
      OpIntOrd OpLt -> "(" <> aStr <> " < " <> bStr <> ")"
      OpIntOrd OpLte -> "(" <> aStr <> " <= " <> bStr <> ")"
      OpBooleanAnd -> "(" <> aStr <> " && " <> bStr <> ")"
      OpBooleanOr -> "(" <> aStr <> " || " <> bStr <> ")"
      _ -> "// Unsupported Op2"
  Accessor base (GetProp k) -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound base <> "." <> sanitizeIdent k <> ".clone().unwrap()"
  Accessor base (GetCtorField qId ctorType (ProperName tyNameStr) (Ident ctorName) propName fieldIdx) ->
    let baseStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound base
        placeholders = String.joinWith ", " (Array.replicate fieldIdx "_")
        prefix = if fieldIdx == 0 then "" else placeholders <> ", "
    in "(match " <> baseStr <> ".clone() { " <> tyNameStr <> "::" <> ctorName <> "(" <> prefix <> "val, ..) => val, _ => unimplemented!() })"
  Var (Qualified mbMod (Ident name)) ->
    let
      modPrefix = case mbMod of
        Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
        Nothing -> ""
      fullName = sanitizeIdent (modPrefix <> name)
      isZeroArity = case Map.lookup fullName bound of
        Just (Func _ _) -> false
        Just _ -> true
        Nothing -> fullName /= "Effect_Console_log"
    in if isZeroArity then fullName <> "()" else fullName
  Let (Just (Ident name)) _ val body ->
    let
      valCode = codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val
      bodyVars = freeVariables body
      comment = if Set.member name bodyVars 
                then "// Perceus Liveness: variable '" <> name <> "' is used in body"
                else "// Perceus Liveness: variable '" <> name <> "' is dead"
    in
      "{\n" <> 
      "    " <> comment <> "\n" <>
      "    let " <> name <> " = " <> valCode <> ";\n" <>
      "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n" <>
      "}"
  Let Nothing _ val body ->
    "{\n" <> 
    "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val <> ";\n" <>
    "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n" <>
    "}"
  EffectBind mbIdent _ val body ->
    case mbIdent of
      Just (Ident name) ->
        "{\n" <>
        "    let " <> name <> " = " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val <> ";\n" <>
        "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n" <>
        "}"
      Nothing ->
        "{\n" <>
        "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val <> ";\n" <>
        "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n" <>
        "}"
  EffectPure val -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val
  Local (Just (Ident name)) _ -> name
  Lit lit -> case lit of
    LitInt i -> "mk_int(" <> show i <> ")"
    LitNumber n -> show n <> " /* f64 */"
    LitString s -> "unsafe_coerce(\"" <> s <> "\")"
    LitChar c -> show c
    LitBoolean b -> if b then "true" else "false"
    LitArray arr -> "vec![" <> String.joinWith ", " (map (codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound) arr) <> "]"
    LitRecord props ->
      let fieldsMap = Map.fromFoldable (map (\(Prop k v) -> Tuple (sanitizeIdent k) (codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound v)) props)
          getF k = fromMaybe "None" (Map.lookup k fieldsMap <#> \v -> "Some(unsafe_coerce(" <> v <> "))")
      in "perceus_ptr::PerceusPtr::new(Record_a { a: 0, b: " <> getF "b" <> ", c: " <> getF "c" <> ", ccc: " <> getF "ccc" <> ", d: " <> getF "d" <> ", x: " <> getF "x" <> ", Applicative0: " <> getF "Applicative0" <> ", pure: " <> getF "pure" <> ", show: " <> getF "show" <> ", discard: " <> getF "discard" <> " })"
  Abs params body -> 
    let
      paramsArr = map (\(Tuple mbId _) -> case mbId of
        Just (Ident n) -> sanitizeIdent n
        _ -> "_") (NonEmptyArray.toArray params)
      paramsCode = String.joinWith ", " (map (\p -> (if p == "_" then "" else "mut ") <> p <> ": UnknownType") paramsArr)
    in "unsafe_coerce(std::rc::Rc::new(move |" <> paramsCode <> "| -> UnknownType {\n" <>
       "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound body <> "\n" <>
       "}))"
  PrimUndefined -> "unimplemented!()"
  CtorSaturated _ _ (ProperName tyNameStr) (Ident ctorName) fields ->
    let fieldsCode = if Array.null fields then "" else 
          "(" <> String.joinWith ", " (map (\(Tuple _ val) -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop bound val) fields) <> ")"
    in tyNameStr <> "::" <> ctorName <> fieldsCode
  CtorDef _ _ _ _ -> "unsafe_coerce(0)"
  _ -> "// Unsupported Expr: " <> printAST (NeutralExpr expr)

printAST :: NeutralExpr -> String
printAST (NeutralExpr expr) = case expr of
  App fn _ -> "App(" <> printAST fn <> ")"
  Lit _ -> "Lit"
  Var _ -> "Var(...)"
  Let _ _ _ _ -> "Let(...)"
  Local _ _ -> "Local(...)"
  Abs _ inner -> "Abs(..., " <> printAST inner <> ")"
  Typed _ inner -> "Typed(" <> printAST inner <> ")"
  EffectBind _ _ _ _ -> "EffectBind"
  EffectPure _ -> "EffectPure"
  Update _ _ -> "Update"
  Accessor inner prop -> "Accessor(" <> printAST inner <> ")"
  UncurriedEffectApp fn _ -> "UncurriedEffectApp(" <> printAST fn <> ")"
  LetRec _ _ inner -> "LetRec(..., " <> printAST inner <> ")"
  Branch _ _ -> "Branch(...)"
  PrimOp _ -> "PrimOp(...)"
  UncurriedApp fn _ -> "UncurriedApp(" <> printAST fn <> ")"
  CtorSaturated _ _ _ _ _ -> "CtorSaturated(...)"
  UncurriedAbs _ inner -> "UncurriedAbs(..., " <> printAST inner <> ")"
  UncurriedEffectAbs _ inner -> "UncurriedEffectAbs(..., " <> printAST inner <> ")"
  CtorDef _ _ _ _ -> "CtorDef"
  EffectDefer inner -> "EffectDefer(" <> printAST inner <> ")"
  PrimEffect _ -> "PrimEffect(...)"
  PrimUndefined -> "PrimUndefined"
  Fail msg -> "Fail(" <> msg <> ")"

freeVariables :: NeutralExpr -> Set String
freeVariables (NeutralExpr expr) = case expr of
  Var (Qualified _ (Ident name)) -> Set.singleton name
  App fn args -> 
    Array.foldl (\acc a -> Set.union acc (freeVariables a)) (freeVariables fn) (NonEmptyArray.toArray args)
  Let (Just (Ident i)) _ val body ->
    Set.union (freeVariables val) (Set.delete i (freeVariables body))
  Let Nothing _ val body ->
    Set.union (freeVariables val) (freeVariables body)
  Typed _ inner -> freeVariables inner
  _ -> Set.empty

inferTypeExpr :: String -> Map.Map String ExprType -> Map.Map String ExprType -> NeutralExpr -> ExprType
inferTypeExpr currentMod aritiesMap bound (NeutralExpr expr) = case expr of
  App fn args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func argTypes retTy -> 
        let expectedCount = Array.length argTypes
            providedCount = NonEmptyArray.length args
        in if expectedCount > providedCount then
             Func (Array.drop providedCount argTypes) retTy
           else retTy
      _ -> Any
  UncurriedApp fn _args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func _ retTy -> retTy
      _ -> Any
  UncurriedEffectApp fn args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func _ retTy -> retTy
      _ -> Any
  LetRec _ _ inner -> inferTypeExpr currentMod aritiesMap bound inner
  Branch _ _ -> Any
  Typed Any inner -> inferTypeExpr currentMod aritiesMap bound inner
  Typed (TypeVar _) inner -> inferTypeExpr currentMod aritiesMap bound inner
  Typed t _ -> t
  CtorSaturated _ _ (ProperName tyNameStr) _ _ -> ADT ["Main", tyNameStr] []
  Var (Qualified mbMod (Ident name)) -> 
    let
      modPrefix = case mbMod of
        Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
        Nothing -> ""
      fullName = modPrefix <> sanitizeIdent name
    in case Map.lookup name bound of
      Just ty -> ty
      Nothing -> case Map.lookup fullName aritiesMap of
        Just ty -> ty
        Nothing -> Any
  Let (Just (Ident i)) _ val body -> inferTypeExpr currentMod aritiesMap (Map.insert i (inferTypeExpr currentMod aritiesMap bound val) bound) body
  _ -> Any

sanitizeIdent :: String -> String
sanitizeIdent s = 
  let s1 = String.replaceAll (Pattern "'") (Replacement "_prime") s
      s2 = String.replaceAll (Pattern "$") (Replacement "_dollar_") s1
  in if s2 == "type" then "type_kw" 
     else if s2 == "fn" then "fn_kw" 
     else s2

dedupArgs :: Array String -> Array String
dedupArgs arr =
  let
    step acc item =
      let count = Map.lookup item acc.counts
      in case count of
        Nothing ->
          { result: Array.snoc acc.result item, counts: Map.insert item 1 acc.counts }
        Just c ->
          let newItem = item <> "_" <> show c
          in { result: Array.snoc acc.result newItem, counts: Map.insert item (c + 1) acc.counts }
  in (Array.foldl step { result: [], counts: Map.empty } arr).result
