module Purust.CodeGen where
import Debug as Debug

import Prelude
import PureScript.Backend.Optimizer.Syntax (BackendSyntax(..), BackendAccessor(..), BackendOperator(..), BackendOperator1(..), BackendOperator2(..), BackendOperatorNum(..), BackendOperatorOrd(..), Pair(..), Level(..))
import PureScript.Backend.Optimizer.Convert (BackendModule, BackendBindingGroup)
import PureScript.Backend.Optimizer.Semantics (NeutralExpr(..))
import PureScript.Backend.Optimizer.CoreFn (Ann(..), Module(..), Ident(..), ExprType(..), DataDecl, Literal(..), Qualified(..), ModuleName(..), Prop(..), ProperName(..))
import Data.String as String
import Data.Array as Array
import Data.Array.NonEmpty as NonEmptyArray
import Data.Foldable (foldMap)
import Data.Newtype (unwrap)
import Data.Maybe (Maybe(..))
import Data.Tuple (Tuple(..))
import Data.Set (Set)
import Data.Set as Set
import Data.Map (Map)
import Data.Map as Map
import Data.String.Pattern (Pattern(..), Replacement(..))
import Data.Maybe (Maybe(..), fromMaybe)
import Partial.Unsafe (unsafeCrashWith)

codegenModule :: Module Ann -> BackendModule -> String
codegenModule (Module coreFnMod) backendMod =
  let
    modNameStr = String.replaceAll (Pattern ".") (Replacement "_") (unwrap backendMod.name)
    
    -- Traduction des DataDecls
    dataDeclsCode = foldMap (\(decl :: DataDecl) ->
        "// Enum for ADT: " <> decl.name <> "\n" <>
        "#[derive(Clone)]\npub enum " <> String.replaceAll (Pattern ".") (Replacement "_") (unwrap backendMod.name) <> "_" <> decl.name <> " {\n" <>
        String.joinWith "" (map (\ctor ->
          let fields' = if Array.null ctor.fields then "" 
                       else "(" <> String.joinWith ", " (map (codegenExprType true) ctor.fields) <> ")"
          in "    " <> ctor.name <> fields' <> ",\n"
        ) decl.constructors) <>
        "}\n\n"
      ) backendMod.dataDecls <>
      "#[derive(Clone, Default)]\npub struct Record_a {\n" <>
      "    pub a: i64,\n" <>
      "    pub b: Option<UnknownType>,\n" <>
      "    pub c: Option<UnknownType>,\n" <>
      "    pub ccc: Option<UnknownType>,\n" <>
      "    pub d: Option<UnknownType>,\n" <>
      "    pub x: Option<UnknownType>,\n" <>
      "    pub Applicative0: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub pure: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub discard: Option<std::rc::Rc<dyn Fn(UnknownType, UnknownType, UnknownType) -> UnknownType>>,\n" <>
      "    pub show: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub proof: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "    pub call: Option<std::rc::Rc<dyn Fn(UnknownType) -> UnknownType>>,\n" <>
      "}\n\n"
      
    -- Traduction des Bindings
    bindingsRes = Array.foldl (\acc group -> 
      let res = codegenBindingGroup modNameStr Set.empty Set.empty acc.arities group
      in { code: acc.code <> res.code, arities: res.arities }
    ) { code: "", arities: Map.empty } backendMod.bindings
    
    bindingsCode = bindingsRes.code
    
  in
    "#![allow(warnings)]\n" <>
    "// Code generated by purust for module " <> modNameStr <> "\n\n" <>
    "use perceus_ptr::PerceusPtr;\n\n" <>
    "pub type UnknownType = perceus_ptr::PerceusPtr<Record_a>;\n\n" <>
    "pub fn unsafe_coerce(x: UnknownType) -> UnknownType { x }\n" <>
    "pub fn unsafe_coerce_type<T>(_: T) -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() }) }\n\n" <>
    "pub fn mk_int(val: i64) -> UnknownType { perceus_ptr::PerceusPtr::new(Record_a { a: val, ..Default::default() }) }\n\n" <>
                    "// Data declarations:\n" <>
    dataDeclsCode <>
    "// Bindings:\n" <>
    bindingsCode
    
codegenExprType :: Boolean -> ExprType -> String
codegenExprType isRet = case _ of
  Func args ret -> "std::rc::Rc<dyn Fn(" <> String.joinWith ", " (map (codegenExprType false) args) <> ") -> " <> codegenExprType true ret <> ">"
  Any -> "UnknownType"
  Record _ -> "UnknownType"
  Array _ -> "UnknownType"
  String -> "String"
  Int -> "i64"
  Number -> "f64"
  Boolean -> "bool"
  Char -> "char"
  ADT _ name _ | Array.last name == Just "Boolean" -> "bool"
  ADT _ name _ -> "UnknownType"
  TypeVar _ -> "UnknownType"
  _ -> "UnknownType"

codegenBindingGroup :: String -> Set.Set String -> Set.Set String -> Map.Map String ExprType -> BackendBindingGroup Ident NeutralExpr -> { code :: String, arities :: Map.Map String ExprType }
codegenBindingGroup modNameStr allZeroArity allMacroBindings aritiesMap group =
  let
    isSelfRecursive = group.recursive && Array.length group.bindings == 1
    
    groupArities = Map.fromFoldable $ map (\(Tuple ident expr) -> 
        let rawIdentName = case ident of
              Ident i -> sanitizeIdent i
              _ -> "unknown"
            identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
            inferredTy = inferTypeExpr modNameStr aritiesMap Map.empty expr
        in Tuple identName inferredTy
      ) group.bindings
      
    mergedArities = Map.union groupArities aritiesMap
    
    code = foldMap (\(Tuple ident expr) ->
      let
        rawIdentName = case ident of
          Ident i -> sanitizeIdent (String.replaceAll (Pattern ".") (Replacement "_") i)
          _ -> "unknown"
        identName = if rawIdentName == "main" then "main" else modNameStr <> "_" <> rawIdentName
        inferredType = fromMaybe Any (Map.lookup identName groupArities)
        innerExpr = case expr of
           NeutralExpr (Typed _ inner) -> inner
           NeutralExpr inner -> NeutralExpr inner
           _ -> expr
        { paramsCode, retCode, bodyCode, isFunc } = case inferredType of
          Func argTypes retType ->
            let
              paramsArr = case innerExpr of
                NeutralExpr (Abs params _) -> map (\(Tuple mbId _) -> case mbId of
                  Just (Ident n) -> n
                  _ -> "_") (NonEmptyArray.toArray params)
                _ -> Array.mapWithIndex (\i _ -> "a" <> show i) argTypes
              deduped = dedupArgs paramsArr
              mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
              paramPairs = Array.zip deduped argTypes
              pCode = String.joinWith ", " $ map (\(Tuple pName ty) ->
                let p = sanitizeIdent pName in
                (if p == "_" then "" else "mut ") <> p <> ": " <> codegenExprType true ty) paramPairs
              bound = Map.fromFoldable (map (\(Tuple k v) -> Tuple (if k == "_" then "_" else k) v) paramPairs)
              bodyCodeRaw = case innerExpr of
                NeutralExpr (Abs _ body) -> codegenExpr modNameStr allZeroArity allMacroBindings mbLoop aritiesMap (Map.union bound aritiesMap) Set.empty body
                _ -> 
                   let fnCode = codegenExpr modNameStr allZeroArity allMacroBindings mbLoop aritiesMap (Map.union bound aritiesMap) Set.empty innerExpr
                       argsCodeArray = map (\p -> sanitizeIdent p <> ".clone()") deduped
                   in Array.foldl (\acc argCode -> "(" <> acc <> ").call.clone().unwrap()(" <> argCode <> ")") fnCode argsCodeArray
            in { paramsCode: pCode, retCode: codegenExprType true retType, bodyCode: bodyCodeRaw, isFunc: true }
          _ -> 
            let isAbs = case innerExpr of
                  NeutralExpr (Abs _ _) -> true
                  _ -> false
            in if isAbs then
              let
                params = case innerExpr of
                  NeutralExpr (Abs p _) -> p
                  _ -> unsafeCrashWith "impossible"
                paramsArr = map (\(Tuple mbId _) -> case mbId of
                  Just (Ident n) -> n
                  _ -> "_") (NonEmptyArray.toArray params)
                deduped = dedupArgs paramsArr
                mbLoop = if isSelfRecursive then Just { name: identName, params: deduped } else Nothing
                pCode = String.joinWith ", " $ map (\pName ->
                  let p = sanitizeIdent pName in
                  (if p == "_" then "" else "mut ") <> p <> ": UnknownType") deduped
                bound = Map.empty
                body = case innerExpr of
                  NeutralExpr (Abs _ b) -> b
                  _ -> unsafeCrashWith "impossible"
              in { paramsCode: pCode, retCode: "UnknownType", bodyCode: codegenExpr modNameStr allZeroArity allMacroBindings mbLoop aritiesMap (Map.union bound aritiesMap) Set.empty body, isFunc: true }
            else
              { paramsCode: "", retCode: codegenExprType true inferredType, bodyCode: codegenExpr modNameStr allZeroArity allMacroBindings Nothing aritiesMap aritiesMap Set.empty expr, isFunc: false }
        
        bodyCodeWithLoop = if isSelfRecursive && isFunc then
            "    let mut _tco_loop = true;\n" <>
            "    while _tco_loop {\n" <>
            "        _tco_loop = false;\n" <>
            "        " <> bodyCode <> "\n" <>
            "    }"
          else bodyCode
          
        bodyCodeFinal = bodyCodeWithLoop
      in
        if identName == "main" then
          "pub fn main() {\n" <>
          "    // AST: " <> printAST expr <> "\n" <>
          "    " <> bodyCodeFinal <> ";\n" <>
          "}\n\n"
        else
          "pub fn " <> identName <> "(" <> paramsCode <> ")" <> (if retCode == "" then "" else " -> " <> retCode) <> " {\n" <>
          "    // AST: " <> printAST expr <> "\n" <>
          bodyCodeFinal <> "\n" <>
          "}\n\n"
    ) group.bindings
  in { code: code, arities: mergedArities }



getTyPrefix :: forall a. String -> Qualified a -> String
getTyPrefix currentMod (Qualified mbMod _) = case mbMod of
  Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
  Nothing -> String.replaceAll (Pattern ".") (Replacement "_") currentMod <> "_"

codegenExpr :: String -> Set.Set String -> Set.Set String -> Maybe { name :: String, params :: Array String } -> Map.Map String ExprType -> Map.Map String ExprType -> Set.Set String -> NeutralExpr -> String
codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive (NeutralExpr expr) = case expr of
  Typed _ inner -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive inner

  App fn args -> 
    let getInner :: NeutralExpr -> NeutralExpr
        getInner (NeutralExpr (Typed _ inner)) = getInner inner
        getInner e = e
        isTopLevelFn = case getInner fn of
                 NeutralExpr (Var (Qualified mbMod (Ident name))) -> 
                   let modPrefix = case mbMod of
                         Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
                         Nothing -> ""
                       fullName = modPrefix <> sanitizeIdent name
                   in Map.member (if fullName == "main" then "main" else fullName) aritiesMap
                 _ -> false
                 
        argsArray = NonEmptyArray.toArray args
        argsFree = map freeVariables argsArray
        aliveForFn = Set.union alive (Array.foldl Set.union Set.empty argsFree)
        fnCode = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForFn fn
        
        argsCodeArray = Array.mapWithIndex (\i arg -> 
            let subsequentArgsFree = Array.drop (i + 1) argsFree
                aliveForArg = Set.union alive (Array.foldl Set.union Set.empty subsequentArgsFree)
            in codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForArg arg
          ) argsArray
        argsCode = String.joinWith ", " argsCodeArray
        
        fnTy = inferTypeExpr currentMod aritiesMap bound fn
        fnArity = case fnTy of
          Func a _ -> Array.length a
          _ -> 0
        
        numProvided = Array.length (NonEmptyArray.toArray args)
    in if isTopLevelFn then
         if fnArity > numProvided then
           let numMissing = fnArity - numProvided
               missingVars = Array.mapWithIndex (\i _ -> "c_" <> show i) (Array.replicate numMissing unit)
               missingArgs = String.joinWith ", " (map (\v -> "mut " <> v <> ": UnknownType") missingVars)
               closureArgs = String.joinWith ", " (argsCodeArray <> missingVars)
           in "perceus_ptr::PerceusPtr::new(Record_a { call: Some(std::rc::Rc::new(move |" <> missingArgs <> "| -> UnknownType {\n    (" <> fnCode <> ")(" <> closureArgs <> ")\n})), ..Default::default() })"
         else
           "(" <> fnCode <> ")(" <> argsCode <> ")"
       else
         Array.foldl (\acc argCode -> "(" <> acc <> ").call.clone().unwrap()(" <> argCode <> ")") fnCode argsCodeArray
  UncurriedEffectApp fn args -> 
    case fn of
      NeutralExpr (Typed _ (NeutralExpr (Accessor _ (GetProp "logRecord")))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Accessor _ (GetProp "logRecord")) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Typed _ (NeutralExpr (Var (Qualified _ (Ident "logRecord"))))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      NeutralExpr (Var (Qualified _ (Ident "logRecord"))) -> 
        let arg0 = Array.head args
        in case arg0 of
             Just a0 -> "println!(\"{}\", " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive a0 <> ".a);"
             Nothing -> "// Unsupported UncurriedEffectApp without args\n"
      _ -> "unimplemented!() /* Unsupported UncurriedEffectApp with fn: " <> printAST fn <> " */\n"

  Update base props ->
    let
      propsCode = map (\(Prop k v) -> "_mut." <> k <> " = Some(std::rc::Rc::new(|_| " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive v <> "));") props
    in
      "{\n" <>
      "    let mut _base = " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive base <> ";\n" <>
      "    {\n" <>
      "        let _mut = perceus_ptr::PerceusPtr::make_mut(&mut _base);\n" <>
      "        " <> String.joinWith "\n        " propsCode <> "\n" <>
      "    }\n" <>
      "    _base\n" <>
      "}"
  Branch branches def ->
    let
      branchCode = map (\(Pair cond body) -> 
        let aliveForCond = Set.union alive (freeVariables body)
        in "if " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForCond cond <> " {\n        " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive body <> "\n    }") (NonEmptyArray.toArray branches)
      defCode = "{\n        " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive def <> "\n    }"
    in
      String.joinWith " else " branchCode <> " else " <> defCode
  PrimOp (Op1 op a) ->
    let aStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive a
    in case op of
      OpBooleanNot -> "!" <> aStr
      OpIntNegate -> "-" <> aStr
      OpNumberNegate -> "-" <> aStr
      OpArrayLength -> "((" <> aStr <> ").len() as i32)"
      _ -> "unimplemented!() /* Unsupported Op1 */"
  PrimOp (Op2 op a b) ->
    let aliveForA = Set.union alive (freeVariables b)
        aStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForA a
        bStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive b
    in case op of
      OpIntNum OpAdd -> "mk_int((" <> aStr <> ").a + (" <> bStr <> ").a)"
      OpIntNum OpSubtract -> "mk_int((" <> aStr <> ").a - (" <> bStr <> ").a)"
      OpIntNum OpMultiply -> "mk_int((" <> aStr <> ").a * (" <> bStr <> ").a)"
      OpIntNum OpDivide -> "mk_int((" <> aStr <> ").a / (" <> bStr <> ").a)"
      OpIntOrd OpEq -> "((" <> aStr <> ").a == (" <> bStr <> ").a)"
      OpIntOrd OpNotEq -> "(" <> aStr <> " != " <> bStr <> ")"
      OpIntOrd OpGt -> "(" <> aStr <> " > " <> bStr <> ")"
      OpIntOrd OpGte -> "(" <> aStr <> " >= " <> bStr <> ")"
      OpIntOrd OpLt -> "(" <> aStr <> " < " <> bStr <> ")"
      OpIntOrd OpLte -> "(" <> aStr <> " <= " <> bStr <> ")"
      OpNumberOrd OpEq -> "((" <> aStr <> ") == (" <> bStr <> "))"
      OpNumberOrd OpNotEq -> "((" <> aStr <> ") != (" <> bStr <> "))"
      OpNumberOrd OpLt -> "((" <> aStr <> ") < (" <> bStr <> "))"
      OpNumberOrd OpLte -> "((" <> aStr <> ") <= (" <> bStr <> "))"
      OpNumberOrd OpGt -> "((" <> aStr <> ") > (" <> bStr <> "))"
      OpNumberOrd OpGte -> "((" <> aStr <> ") >= (" <> bStr <> "))"
      OpStringOrd OpEq -> "((" <> aStr <> ") == (" <> bStr <> "))"
      OpStringOrd OpNotEq -> "((" <> aStr <> ") != (" <> bStr <> "))"
      OpCharOrd OpEq -> "((" <> aStr <> ") == (" <> bStr <> "))"
      OpCharOrd OpNotEq -> "((" <> aStr <> ") != (" <> bStr <> "))"
      OpBooleanOrd OpEq -> "((" <> aStr <> ") == (" <> bStr <> "))"
      OpBooleanOrd OpNotEq -> "((" <> aStr <> ") != (" <> bStr <> "))"
      OpBooleanAnd -> "(" <> aStr <> " && " <> bStr <> ")"
      OpBooleanOr -> "(" <> aStr <> " || " <> bStr <> ")"
      _ -> "unimplemented!() /* Unsupported Op2 */"
  Accessor base (GetProp k) -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive base <> "." <> sanitizeIdent k <> ".clone().unwrap()(unsafe_coerce_type(0))"
  Accessor base (GetCtorField qId ctorType (ProperName tyNameStr) (Ident ctorName) propName fieldIdx) ->
    let baseStr = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive base
        placeholders = String.joinWith ", " (Array.replicate fieldIdx "_")
        prefix = if fieldIdx == 0 then "" else placeholders <> ", "
        fullTyName = getTyPrefix currentMod qId <> tyNameStr
    in "(match " <> baseStr <> " { " <> fullTyName <> "::" <> ctorName <> "(" <> prefix <> "val, ..) => val, _ => unimplemented!() })"
  Var (Qualified mbMod (Ident name)) ->
    let
      modPrefix = case mbMod of
        Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
        Nothing -> ""
      fullName = sanitizeIdent (modPrefix <> name)
      isZeroArity = case Map.lookup fullName bound of
        Just (Func _ _) -> false
        Just _ -> true
        Nothing -> case Map.lookup fullName aritiesMap of
          Just (Func _ _) -> false
          Just _ -> true
          Nothing -> fullName /= "Effect_Console_log"
      isAlive = Set.member fullName alive
      varCode = if isZeroArity then fullName <> "()" else fullName
    in if isAlive then varCode <> ".dup()" else varCode
  Let mbId lvl val body ->
    let
      name = case mbId of
        Just (Ident nameRaw) -> sanitizeIdent nameRaw
        Nothing -> "lvl_" <> show (unwrap lvl)
      bodyVars = freeVariables body
      aliveForVal = Set.union alive bodyVars
      valCode = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForVal val
      -- if name is not in bodyVars, it's dead immediately
      deadCode = if Set.member name bodyVars then "" else "    " <> name <> ".drop_explicit();\n"
    in
      "{\n" <> 
      "    let mut " <> name <> " = " <> valCode <> ";\n" <>
      deadCode <>
      "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive body <> "\n" <>
      "}"
  EffectBind mbIdent lvl val body ->
    let name = case mbIdent of
          Just (Ident n) -> sanitizeIdent n
          Nothing -> "lvl_" <> show (unwrap lvl)
        aliveForVal = Set.union alive (freeVariables body)
        valCode = codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForVal val
        bodyVars = freeVariables body
        deadCode = if Set.member name bodyVars then "" else "    " <> name <> ".drop_explicit();\n"
    in
    "{\n" <>
    "    let " <> name <> " = " <> valCode <> ";\n" <>
    deadCode <>
    "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive body <> "\n" <>
    "}"
  EffectPure val -> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound alive val
  Local mbId lvl -> 
    let name = case mbId of
          Just (Ident nameRaw) -> sanitizeIdent nameRaw
          Nothing -> "lvl_" <> show (unwrap lvl)
    in if Set.member name alive then name <> ".dup()" else name
  Lit lit -> case lit of
    LitInt i -> "mk_int(" <> show i <> ")"
    LitNumber n -> show n <> " /* f64 */"
    LitString s -> "unsafe_coerce(r#\"" <> s <> "\"#)"
    LitChar c -> show c
    LitBoolean b -> if b then "true" else "false"
    LitArray arr -> 
      let arrCode = Array.mapWithIndex (\i a -> 
            let subsequent = Array.drop (i + 1) arr
                aliveForA = Set.union alive (Array.foldl Set.union Set.empty (map freeVariables subsequent))
            in codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForA a
          ) arr
      in "vec![" <> String.joinWith ", " arrCode <> "]"
    LitRecord props ->
      let fields = String.joinWith ", " (map (\(Prop k v) -> sanitizeIdent k <> ": Some(std::rc::Rc::new(|_| " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound Set.empty v <> "))") props)
      in "perceus_ptr::PerceusPtr::new(Record_a { " <> fields <> (if Array.length props > 0 then ", " else "") <> "..Default::default() })"
  Abs params body -> 
    let
      paramsArr = map (\(Tuple mbId lvl) -> case mbId of
        Just (Ident n) -> sanitizeIdent n
        Nothing -> "lvl_" <> show (unwrap lvl)) (NonEmptyArray.toArray params)
      paramsCode = String.joinWith ", " (map (\p -> (if p == "_" then "" else "mut ") <> p <> ": UnknownType") paramsArr)
      bodyVars = freeVariables body
      capturedVars = let 
          unfiltered = Array.fromFoldable bodyVars :: Array String
          filtered = Array.filter (\v -> not (Map.member v aritiesMap) && not (Set.member v allZeroArity) && not (Array.elem v paramsArr)) unfiltered
        in filtered
      clones = String.joinWith "" (map (\v -> "    let mut " <> v <> " = " <> v <> ".clone();\n") capturedVars)
      drops = String.joinWith "" (map (\p -> if p /= "_" && not (Set.member p bodyVars) then "    " <> p <> ".drop_explicit();\n" else "") paramsArr)
    in "perceus_ptr::PerceusPtr::new(Record_a { call: Some(std::rc::Rc::new(move |" <> paramsCode <> "| -> UnknownType {\n" <>
       clones <> drops <>
       "    " <> codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound Set.empty body <> "\n" <>
       "})), ..Default::default() })"
  PrimUndefined -> "unimplemented!()"
  CtorSaturated qId _ (ProperName tyNameStr) (Ident ctorName) fields ->
    let fieldsCode = if Array.null fields then "" else 
          "(" <> String.joinWith ", " (Array.mapWithIndex (\i (Tuple _ val) -> 
            let subsequent = Array.drop (i + 1) fields
                aliveForV = Set.union alive (Array.foldl Set.union Set.empty (map (\(Tuple _ sv) -> freeVariables sv) subsequent))
            in codegenExpr currentMod allZeroArity allMacroBindings mbLoop aritiesMap bound aliveForV val
          ) fields) <> ")"
        fullTyName = getTyPrefix currentMod qId <> tyNameStr
    in fullTyName <> "::" <> ctorName <> fieldsCode
  CtorDef _ _ _ _ -> "perceus_ptr::PerceusPtr::new(Record_a { ..Default::default() })"
  _ -> "unimplemented!() /* Unsupported Expr: " <> printAST (NeutralExpr expr) <> " */"

printAST :: NeutralExpr -> String
printAST (NeutralExpr expr) = case expr of
  App fn _ -> "App(" <> printAST fn <> ")"
  Lit _ -> "Lit"
  Var _ -> "Var(...)"
  Let _ _ _ _ -> "Let(...)"
  Local _ _ -> "Local(...)"
  Abs _ inner -> "Abs(..., " <> printAST inner <> ")"
  Typed _ inner -> "Typed(" <> printAST inner <> ")"
  EffectBind _ _ _ _ -> "EffectBind"
  EffectPure _ -> "EffectPure"
  Update _ _ -> "Update"
  Accessor inner prop -> "Accessor(" <> printAST inner <> ")"
  UncurriedEffectApp fn _ -> "UncurriedEffectApp(" <> printAST fn <> ")"
  LetRec _ _ inner -> "LetRec(..., " <> printAST inner <> ")"
  Branch _ _ -> "Branch(...)"
  PrimOp _ -> "PrimOp(...)"
  UncurriedApp fn _ -> "UncurriedApp(" <> printAST fn <> ")"
  CtorSaturated _ _ _ _ _ -> "CtorSaturated(...)"
  UncurriedAbs _ inner -> "UncurriedAbs(..., " <> printAST inner <> ")"
  UncurriedEffectAbs _ inner -> "UncurriedEffectAbs(..., " <> printAST inner <> ")"
  CtorDef _ _ _ _ -> "CtorDef"
  EffectDefer inner -> "EffectDefer(" <> printAST inner <> ")"
  PrimEffect _ -> "PrimEffect(...)"
  PrimUndefined -> "PrimUndefined"
  Fail msg -> "Fail(" <> msg <> ")"

freeVariables :: NeutralExpr -> Set String
freeVariables (NeutralExpr expr) = case expr of
  Var (Qualified mbMod (Ident name)) -> 
    let modPrefix = case mbMod of
          Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
          Nothing -> ""
    in Set.singleton (sanitizeIdent (modPrefix <> name))
  Local mbId lvl -> Set.singleton (case mbId of
      Just (Ident nameRaw) -> sanitizeIdent nameRaw
      Nothing -> "lvl_" <> show (unwrap lvl))
  App fn args -> 
    Array.foldl (\acc a -> Set.union acc (freeVariables a)) (freeVariables fn) (NonEmptyArray.toArray args)
  Let mbId lvl val body ->
    let name = case mbId of
          Just (Ident i) -> sanitizeIdent i
          Nothing -> "lvl_" <> show (unwrap lvl)
    in Set.union (freeVariables val) (Set.delete name (freeVariables body))
  Typed _ inner -> freeVariables inner
  Update base props ->
    Array.foldl (\acc (Prop _ v) -> Set.union acc (freeVariables v)) (freeVariables base) props
  Branch branches def ->
    let branchVars = Array.foldl (\acc (Pair cond body) -> Set.union acc (Set.union (freeVariables cond) (freeVariables body))) Set.empty (NonEmptyArray.toArray branches)
    in Set.union branchVars (freeVariables def)
  PrimOp (Op1 _ a) -> freeVariables a
  PrimOp (Op2 _ a b) -> Set.union (freeVariables a) (freeVariables b)
  Accessor base _ -> freeVariables base
  EffectBind mbIdent lvl val body ->
    let name = case mbIdent of
          Just (Ident i) -> sanitizeIdent i
          Nothing -> "lvl_" <> show (unwrap lvl)
        bodyVars = Set.delete name (freeVariables body)
    in Set.union (freeVariables val) bodyVars
  EffectPure val -> freeVariables val
  LetRec _ binds body ->
    let bindsVars = Array.foldl (\acc (Tuple (Ident n) _) -> Set.insert (sanitizeIdent n) acc) Set.empty (NonEmptyArray.toArray binds)
        allValsVars = Array.foldl (\acc (Tuple _ v) -> Set.union acc (freeVariables v)) Set.empty (NonEmptyArray.toArray binds)
    in Set.union allValsVars (Set.difference (freeVariables body) bindsVars)
  Abs params body ->
    let paramsVars = Array.foldl (\acc (Tuple mbId _) -> case mbId of
          Just (Ident n) -> Set.insert (sanitizeIdent n) acc
          _ -> acc) Set.empty (NonEmptyArray.toArray params)
    in Set.difference (freeVariables body) paramsVars
  Fail _ -> Set.empty
  Lit (LitArray arr) -> Array.foldl (\acc a -> Set.union acc (freeVariables a)) Set.empty arr
  Lit (LitRecord props) -> Array.foldl (\acc (Prop _ v) -> Set.union acc (freeVariables v)) Set.empty props
  CtorSaturated _ _ _ _ fields -> Array.foldl (\acc (Tuple _ v) -> Set.union acc (freeVariables v)) Set.empty fields
  _ -> Set.empty

inferTypeExpr :: String -> Map.Map String ExprType -> Map.Map String ExprType -> NeutralExpr -> ExprType
inferTypeExpr currentMod aritiesMap bound (NeutralExpr expr) = case expr of
  App fn args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func argTypes retTy -> 
        let expectedCount = Array.length argTypes
            providedCount = NonEmptyArray.length args
        in if expectedCount > providedCount then
             Func (Array.drop providedCount argTypes) retTy
           else retTy
      _ -> Any
  UncurriedApp fn _args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func _ retTy -> retTy
      _ -> Any
  UncurriedEffectApp fn args -> 
    case inferTypeExpr currentMod aritiesMap bound fn of
      Func _ retTy -> retTy
      _ -> Any
  LetRec _ _ inner -> inferTypeExpr currentMod aritiesMap bound inner
  Branch _ _ -> Any
  Typed Any inner -> inferTypeExpr currentMod aritiesMap bound inner
  Typed (TypeVar _) inner -> inferTypeExpr currentMod aritiesMap bound inner
  Typed t _ -> t
  CtorSaturated _ _ (ProperName tyNameStr) _ _ -> ADT "Main" ["Main", tyNameStr] []
  Var (Qualified mbMod (Ident name)) -> 
    let
      modPrefix = case mbMod of
        Just (ModuleName mn) -> String.replaceAll (Pattern ".") (Replacement "_") mn <> "_"
        Nothing -> ""
      fullName = modPrefix <> sanitizeIdent name
    in case Map.lookup name bound of
      Just ty -> ty
      Nothing -> case Map.lookup fullName aritiesMap of
        Just ty -> ty
        Nothing -> Any
  Let (Just (Ident i)) _ val body -> inferTypeExpr currentMod aritiesMap (Map.insert (sanitizeIdent i) (inferTypeExpr currentMod aritiesMap bound val) bound) body
  _ -> Any

sanitizeIdent :: String -> String
sanitizeIdent s = 
  let s1 = String.replaceAll (Pattern "'") (Replacement "_prime") s
      s2 = String.replaceAll (Pattern "$") (Replacement "_dollar_") s1
  in if s2 == "type" then "type_kw" 
     else if s2 == "fn" then "fn_kw" 
     else if s2 == "break" then "break_kw"
     else if s2 == "mod" then "mod_kw"
     else if s2 == "as" then "as_kw"
     else if s2 == "gen" then "gen_kw"
     else if s2 == "use" then "use_kw"
     else if s2 == "pub" then "pub_kw"
     else if s2 == "ref" then "ref_kw"
     else if s2 == "mut" then "mut_kw"
     else if s2 == "move" then "move_kw"
     else if s2 == "match" then "match_kw"
     else if s2 == "loop" then "loop_kw"
     else s2

dedupArgs :: Array String -> Array String
dedupArgs arr =
  let
    step acc item =
      let count = Map.lookup item acc.counts
      in case count of
        Nothing ->
          { result: Array.snoc acc.result item, counts: Map.insert item 1 acc.counts }
        Just c ->
          let newItem = item <> "_" <> show c
          in { result: Array.snoc acc.result newItem, counts: Map.insert item (c + 1) acc.counts }
  in (Array.foldl step { result: [], counts: Map.empty } arr).result
